import type {Block} from '../types/block.js'
import type {Collection} from '../types/types.js'
import {toSolidSignal} from '../utils.js'

// @deprecated
// Will get replaced with the blocks from the database
export const legacyBlocks: Record<string, Block[]> = {
	default: [
		// Female
		{
			_id: 'default-top',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/female/Avatar-1/Default+Garments/Default+Top.glb',
			blockName: 'Default Top',
			avatar: 'female',
			category: 'Bodice',
			collection: 'default',
			templateId: 'default-top',
			templateName: 'Default Top',
			templateCategory: 'Top',
		},
		{
			_id: 'default-shorts',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/female/Avatar-1/Default+Garments/Default+Shorts.glb',
			blockName: 'Default Shorts',
			avatar: 'female',
			category: 'Pants',
			collection: 'default',
			templateId: 'default-shorts',
			templateName: 'Default Shorts',
			templateCategory: 'Pants',
		},
		{
			_id: 'default-shoes',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/female/Avatar-1/Default+Garments/Shoes.glb',
			blockName: 'Default Shoes',
			avatar: 'female',
			category: 'Shoes',
			collection: 'default',
			templateId: 'default-shoes',
			templateName: 'Default Shoes',
			templateCategory: 'Shoes',
		},
		// Male
		{
			_id: 'default-male-top',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/male/Male+-+Top.glb',
			blockName: 'Default Male Top',
			avatar: 'male',
			category: 'Bodice',
			collection: 'default',
			templateId: 'default-male-top',
			templateName: 'Default Male Top',
			templateCategory: 'Top',
		},
		{
			_id: 'default-male-pants',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/male/Male+-+Pants.glb',
			blockName: 'Default Male Pants',
			avatar: 'male',
			category: 'Pants',
			collection: 'default',
			templateId: 'default-male-pants',
			templateName: 'Default Male Pants',
			templateCategory: 'Pants',
		},
		{
			_id: 'default-male-shoes',
			thumb: '',
			modelFile: '/static/drippy-app/drippy-app-3D/models/male/Shoes.glb',
			blockName: 'Default Male Shoes',
			avatar: 'male',
			category: 'Shoes',
			collection: 'default',
			templateId: 'default-male-shoes',
			templateName: 'Default Male Shoes',
			templateCategory: 'Shoes',
		},
	],
	anyshape: [
		{
			_id: '910c6a1e-7879-41d6-8ade-1aa10ecbd199',
			thumb: '/static/images/anyshape/blocks/Dress_/Item_1___Fullbody/fullbody_1788.webp',
			modelFile: '/static/models/anyshape/blocks/Dress_/Item_1___Fullbody/fullbody_1788.glb',
			blockName: 'fullbody 1788',
			avatar: 'female',
			category: 'Full Body',
			collection: 'anyshape',
			templateId: 'd9ba4aea-9279-4909-b6a5-a348fb32a9d9',
			templateName: 'Item 1',
			templateCategory: 'Dress ',
		},
	],

	ayarabbim: [
		{
			_id: '40d2fbd0-addc-4456-ab03-1133b5a148af',
			thumb: '/static/images/ayarabbim/blocks/Skirt/Item_1_Skirt/skirt_1932.webp',
			modelFile: '/static/models/ayarabbim/blocks/Skirt/Item_1_Skirt/skirt_1932.glb',
			blockName: 'skirt 1932',
			avatar: 'female',
			category: 'Skirt',
			collection: 'ayarabbim',
			templateId: '575e0a9a-b8cb-4ec1-acf2-fe8fdad25c49',
			templateName: 'Item 1',
			templateCategory: 'Skirt',
		},
		{
			_id: 'd6087bcd-b3f5-4ce7-b578-1588933ff6da',
			thumb: '/static/images/ayarabbim/blocks/Top/Item_1_Sleeves/sleeves_1934.webp',
			modelFile: '/static/models/ayarabbim/blocks/Top/Item_1_Sleeves/sleeves_1934.glb',
			blockName: 'sleeves 1934',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'ayarabbim',
			templateId: '50054819-7f4b-46c0-b478-b3b1ccd1ddbd',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
		{
			_id: 'c88525be-812e-4a99-b861-36aac961eab6',
			thumb: '/static/images/ayarabbim/blocks/Top/Item_1_Bodice/bodice_1933.webp',
			modelFile: '/static/models/ayarabbim/blocks/Top/Item_1_Bodice/bodice_1933.glb',
			blockName: 'bodice 1933',
			avatar: 'female',
			category: 'Bodice',
			collection: 'ayarabbim',
			templateId: '50054819-7f4b-46c0-b478-b3b1ccd1ddbd',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	'baum-und-pferdgarten': [
		{
			_id: '8500104a-d926-4439-b4af-434a2a6c40ce',
			thumb: '/static/images/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Sleeves/sleeves_1843-a_pose.webp',
			modelFile: '/static/models/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Sleeves/sleeves_1843-a_pose.glb',
			blockName: 'sleeves 1843-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'baum-und-pferdgarten',
			templateId: 'b190ed3f-fa45-4090-a847-99447b4468be',
			templateName: 'ANDINE DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: '4f9b70a3-4388-4e84-952c-0dbceab3f8a8',
			thumb: '/static/images/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Skirt/skirt_1842-a_pose.webp',
			modelFile: '/static/models/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Skirt/skirt_1842-a_pose.glb',
			blockName: 'skirt 1842-a pose',
			avatar: 'female',
			category: 'Dress',
			collection: 'baum-und-pferdgarten',
			templateId: 'b190ed3f-fa45-4090-a847-99447b4468be',
			templateName: 'ANDINE DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: 'a8d924bd-5d6a-4f92-8cbe-304481f5c2d7',
			thumb: '/static/images/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Bodice/bodice_1841-a_pose.webp',
			modelFile: '/static/models/baum-und-pferdgarten/blocks/Dress/ANDINE_DRESS___Bodice/bodice_1841-a_pose.glb',
			blockName: 'bodice 1841-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'baum-und-pferdgarten',
			templateId: 'b190ed3f-fa45-4090-a847-99447b4468be',
			templateName: 'ANDINE DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: '77cbc1a9-9588-4a05-b05e-d9e73893f0bc',
			thumb: '/static/images/baum-und-pferdgarten/options/Dress/Skirt/Skirt_5.webp',
			modelFile: '/static/models/baum-und-pferdgarten/options/Dress/Skirt/Skirt_5.glb',
			blockName: 'Skirt 5',
			avatar: 'female',
			category: 'Skirt',
			collection: 'baum-und-pferdgarten',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '04eb2884-1ded-48c2-9bb3-c1678932d7dc',
			thumb: '/static/images/baum-und-pferdgarten/options/Dress/Skirt/Skirt_4.webp',
			modelFile: '/static/models/baum-und-pferdgarten/options/Dress/Skirt/Skirt_4.glb',
			blockName: 'Skirt 4',
			avatar: 'female',
			category: 'Skirt',
			collection: 'baum-und-pferdgarten',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'e41430d6-94aa-4654-89e9-7db62c9247e9',
			thumb: '/static/images/baum-und-pferdgarten/options/Dress/Skirt/Skirt_3.webp',
			modelFile: '/static/models/baum-und-pferdgarten/options/Dress/Skirt/Skirt_3.glb',
			blockName: 'Skirt 3',
			avatar: 'female',
			category: 'Skirt',
			collection: 'baum-und-pferdgarten',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'f47bd45c-d24f-4091-b60c-ed1f780b70ca',
			thumb: '/static/images/baum-und-pferdgarten/options/Dress/Skirt/Skirt_2.webp',
			modelFile: '/static/models/baum-und-pferdgarten/options/Dress/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'baum-und-pferdgarten',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '2973136a-fa7d-4cbc-9146-ae01615c4bf1',
			thumb: '/static/images/baum-und-pferdgarten/options/Dress/Skirt/Skirt_1.webp',
			modelFile: '/static/models/baum-und-pferdgarten/options/Dress/Skirt/Skirt_1.glb',
			blockName: 'Skirt 1',
			avatar: 'female',
			category: 'Skirt',
			collection: 'baum-und-pferdgarten',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'bloom.womenswear': [
		{
			_id: '3ef5350d-df73-41d4-80e3-a3d2b61634c5',
			thumb: '/static/images/bloom.womenswear/blocks/Dress/Item_1___Bodice/bodice_1750-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Dress/Item_1___Bodice/bodice_1750-a_pose.glb',
			blockName: 'bodice 1750-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'bloom.womenswear',
			templateId: '84027586-b9fa-48e1-8e5f-89953e3cc61b',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
		{
			_id: '8de50f18-6810-4cae-bd02-90ab7cc75db3',
			thumb: '/static/images/bloom.womenswear/blocks/Dress/Item_1___Skirt/skirt_1751-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Dress/Item_1___Skirt/skirt_1751-a_pose.glb',
			blockName: 'skirt 1751-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'bloom.womenswear',
			templateId: '84027586-b9fa-48e1-8e5f-89953e3cc61b',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
		{
			_id: '389a7fb1-90bb-44b7-84a0-915573aa7522',
			thumb: '/static/images/bloom.womenswear/blocks/Skirt/Item_2___Skirt/skirt_1753-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Skirt/Item_2___Skirt/skirt_1753-a_pose.glb',
			blockName: 'skirt 1753-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'bloom.womenswear',
			templateId: '54019ac4-d644-422e-882e-a30933a14e16',
			templateName: 'Item 2',
			templateCategory: 'Skirt',
		},
		{
			_id: '0e31449b-8b88-4dca-97c7-52cc4fda50b7',
			thumb: '/static/images/bloom.womenswear/blocks/Skirt/Item_1___Skirt/skirt_1749-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Skirt/Item_1___Skirt/skirt_1749-a_pose.glb',
			blockName: 'skirt 1749-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'bloom.womenswear',
			templateId: '568f31ea-c5fe-4805-a772-e05474bcb440',
			templateName: 'Item 1',
			templateCategory: 'Skirt',
		},
		{
			_id: 'ca99ae8d-f6f6-4cfc-bf2d-c8990af615b9',
			thumb: '/static/images/bloom.womenswear/blocks/Top/Item_2___Bodice/bodice_1752-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Top/Item_2___Bodice/bodice_1752-a_pose.glb',
			blockName: 'bodice 1752-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'bloom.womenswear',
			templateId: '24b5fca3-8976-448a-9d36-1a4630ecbcaa',
			templateName: 'Item 2',
			templateCategory: 'Top',
		},
		{
			_id: 'edbd1e4d-397e-4926-9135-4949f0296267',
			thumb: '/static/images/bloom.womenswear/blocks/Top/Item_1___Bodice/bodice_1748-a_pose.webp',
			modelFile: '/static/models/bloom.womenswear/blocks/Top/Item_1___Bodice/bodice_1748-a_pose.glb',
			blockName: 'bodice 1748-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'bloom.womenswear',
			templateId: '2681e8eb-30cc-447e-a081-fbc5ba8a171b',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	bupbes: [
		{
			_id: '60dddac5-6b83-4d50-aca9-fa6b528ceac4',
			thumb: '/static/images/bupbes/blocks/Dress/Item_1_Fullbody/fullbody_1892.webp',
			modelFile: '/static/models/bupbes/blocks/Dress/Item_1_Fullbody/fullbody_1892.glb',
			blockName: 'fullbody 1892',
			avatar: 'female',
			category: 'Full Body',
			collection: 'bupbes',
			templateId: 'f937a929-a87d-42d3-8388-ee5a424e4e2b',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'call-me-ari': [
		{
			_id: '2ccac98f-5e3a-4554-b082-9e4d10453244',
			thumb: '/static/images/call-me-ari/blocks/Dress/KATIE_MAXI_DRESS_Skirt/skirt_1940.webp',
			modelFile: '/static/models/call-me-ari/blocks/Dress/KATIE_MAXI_DRESS_Skirt/skirt_1940.glb',
			blockName: 'skirt 1940',
			avatar: 'female',
			category: 'Dress',
			collection: 'call-me-ari',
			templateId: 'b123090f-ede6-4661-b64b-8fbbc495c890',
			templateName: 'KATIE MAXI DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: 'd77d20f9-69d8-42bd-b160-42d5d73bd89d',
			thumb: '/static/images/call-me-ari/blocks/Dress/KATIE_MAXI_DRESS_Bodice/bodice_1939.webp',
			modelFile: '/static/models/call-me-ari/blocks/Dress/KATIE_MAXI_DRESS_Bodice/bodice_1939.glb',
			blockName: 'bodice 1939',
			avatar: 'female',
			category: 'Bodice',
			collection: 'call-me-ari',
			templateId: 'b123090f-ede6-4661-b64b-8fbbc495c890',
			templateName: 'KATIE MAXI DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: 'f715fa05-b376-4592-ab12-57be7ef6b81b',
			thumb: '/static/images/call-me-ari/options/Dress/Skirt/Skirt_5.webp',
			modelFile: '/static/models/call-me-ari/options/Dress/Skirt/Skirt_5.glb',
			blockName: 'Skirt 5',
			avatar: 'female',
			category: 'Skirt',
			collection: 'call-me-ari',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'ec509bce-8773-413b-ab09-a2da8961c45e',
			thumb: '/static/images/call-me-ari/options/Dress/Skirt/Skirt_4.webp',
			modelFile: '/static/models/call-me-ari/options/Dress/Skirt/Skirt_4.glb',
			blockName: 'Skirt 4',
			avatar: 'female',
			category: 'Skirt',
			collection: 'call-me-ari',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '7b2fc3bf-e889-467e-856f-2522dea37e85',
			thumb: '/static/images/call-me-ari/options/Dress/Skirt/Skirt_3.webp',
			modelFile: '/static/models/call-me-ari/options/Dress/Skirt/Skirt_3.glb',
			blockName: 'Skirt 3',
			avatar: 'female',
			category: 'Skirt',
			collection: 'call-me-ari',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '66c8c7db-f11b-45d5-8e94-fc7fe68c2eab',
			thumb: '/static/images/call-me-ari/options/Dress/Skirt/Skirt_2.webp',
			modelFile: '/static/models/call-me-ari/options/Dress/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'call-me-ari',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'f7121792-1f18-47e1-aea4-0a2f8d3a71e0',
			thumb: '/static/images/call-me-ari/options/Dress/Skirt/Skirt_1.webp',
			modelFile: '/static/models/call-me-ari/options/Dress/Skirt/Skirt_1.glb',
			blockName: 'Skirt 1',
			avatar: 'female',
			category: 'Skirt',
			collection: 'call-me-ari',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'cecilie-bahnsen': [
		{
			_id: '13f72b4a-9b01-4b17-94ee-6467e45f8b2c',
			thumb: '/static/images/cecilie-bahnsen/blocks/Dress/Bosco_Dress___Fullbody/fullbody_1820.webp',
			modelFile: '/static/models/cecilie-bahnsen/blocks/Dress/Bosco_Dress___Fullbody/fullbody_1820.glb',
			blockName: 'fullbody 1820',
			avatar: 'female',
			category: 'Dress',
			collection: 'cecilie-bahnsen',
			templateId: 'd3e061c3-3d87-42a3-88f2-d59188dd0a9d',
			templateName: 'Bosco Dress',
			templateCategory: 'Dress',
		},
	],

	'cuba-vera': [
		{
			_id: '2c2afde8-d50c-427c-93c3-c05a87deff58',
			thumb: '/static/images/cuba-vera/blocks/Dress/Pink_Dress_Fullbody/fullbody_1925.webp',
			modelFile: '/static/models/cuba-vera/blocks/Dress/Pink_Dress_Fullbody/fullbody_1925.glb',
			blockName: 'fullbody 1925',
			avatar: 'female',
			category: 'Dress',
			collection: 'cuba-vera',
			templateId: 'be2999ef-dcde-494e-99ca-9538de41d3fd',
			templateName: 'Pink Dress',
			templateCategory: 'Dress',
		},
	],

	'dario-mittmann': [
		{
			_id: 'e83b0f07-e54e-4c91-9246-d4b5866a5db1',
			thumb: '/static/images/dario-mittmann/blocks/Skirt/Saia_Gravata_Colorida___Skirt/skirt_1794-a_pose.webp',
			modelFile: '/static/models/dario-mittmann/blocks/Skirt/Saia_Gravata_Colorida___Skirt/skirt_1794-a_pose.glb',
			blockName: 'skirt 1794-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'dario-mittmann',
			templateId: '28400841-fb02-4a3a-a949-0ea24b41d01b',
			templateName: 'Saia Gravata Colorida',
			templateCategory: 'Skirt',
		},
		{
			_id: 'e9fe5c3c-7c28-433a-9647-d81a258a5d52',
			thumb: '/static/images/dario-mittmann/options/Skirt/Skirt/Skirt_5.webp',
			modelFile: '/static/models/dario-mittmann/options/Skirt/Skirt/Skirt_5.glb',
			blockName: 'Skirt 5',
			avatar: 'female',
			category: 'Skirt',
			collection: 'dario-mittmann',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: 'bb11d44e-7a08-4cd8-8a48-b049d07ea13d',
			thumb: '/static/images/dario-mittmann/options/Skirt/Skirt/Skirt_4.webp',
			modelFile: '/static/models/dario-mittmann/options/Skirt/Skirt/Skirt_4.glb',
			blockName: 'Skirt 4',
			avatar: 'female',
			category: 'Skirt',
			collection: 'dario-mittmann',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: 'cb300200-c69b-4818-9921-806de15f4d67',
			thumb: '/static/images/dario-mittmann/options/Skirt/Skirt/Skirt_3.webp',
			modelFile: '/static/models/dario-mittmann/options/Skirt/Skirt/Skirt_3.glb',
			blockName: 'Skirt 3',
			avatar: 'female',
			category: 'Skirt',
			collection: 'dario-mittmann',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: 'ca8be371-c2b4-4ab3-8fc9-fcd2893f03b6',
			thumb: '/static/images/dario-mittmann/options/Skirt/Skirt/Skirt_2.webp',
			modelFile: '/static/models/dario-mittmann/options/Skirt/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'dario-mittmann',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: '44ddab43-b5e7-40ed-adff-a63a6dbf8af6',
			thumb: '/static/images/dario-mittmann/blocks/Top/Camisa_Alfaiataria_Azul___Sleeves/sleeves_1799-a_pose.webp',
			modelFile: '/static/models/dario-mittmann/blocks/Top/Camisa_Alfaiataria_Azul___Sleeves/sleeves_1799-a_pose.glb',
			blockName: 'sleeves 1799-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'dario-mittmann',
			templateId: 'e3c9aa99-647e-43f1-b64e-8d66cab6fc3b',
			templateName: 'Camisa Alfaiataria Azul',
			templateCategory: 'Top',
		},
		{
			_id: '546a2c01-905f-4787-89fb-5df217b7b18b',
			thumb: '/static/images/dario-mittmann/blocks/Top/Camisa_Alfaiataria_Azul___Bodice/bodice_1798-a_pose.webp',
			modelFile: '/static/models/dario-mittmann/blocks/Top/Camisa_Alfaiataria_Azul___Bodice/bodice_1798-a_pose.glb',
			blockName: 'bodice 1798-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'dario-mittmann',
			templateId: 'e3c9aa99-647e-43f1-b64e-8d66cab6fc3b',
			templateName: 'Camisa Alfaiataria Azul',
			templateCategory: 'Top',
		},
	],

	givenchy: [
		{
			_id: '814f89b7-5ad0-467c-b9e1-718c4773daaf',
			thumb: '/static/images/givenchy/blocks/Dress/Open_back_ruffled_dress_in_mesh_Skirt/skirt_1907-a_pose.webp',
			modelFile: '/static/models/givenchy/blocks/Dress/Open_back_ruffled_dress_in_mesh_Skirt/skirt_1907-a_pose.glb',
			blockName: 'skirt 1907-a pose',
			avatar: 'female',
			category: 'Dress',
			collection: 'givenchy',
			templateId: '68548cf4-29f9-4a2a-806b-01be931099b0',
			templateName: 'Open back ruffled dress in mesh',
			templateCategory: 'Dress',
		},
		{
			_id: 'b7609bd2-6392-4242-a706-abbd59e9ac36',
			thumb: '/static/images/givenchy/blocks/Dress/Open_back_ruffled_dress_in_mesh_Bodice/bodice_1906-a_pose.webp',
			modelFile: '/static/models/givenchy/blocks/Dress/Open_back_ruffled_dress_in_mesh_Bodice/bodice_1906-a_pose.glb',
			blockName: 'bodice 1906-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'givenchy',
			templateId: '68548cf4-29f9-4a2a-806b-01be931099b0',
			templateName: 'Open back ruffled dress in mesh',
			templateCategory: 'Dress',
		},
		{
			_id: '09f6ab10-0467-4b83-ab3a-95ded0fe26e0',
			thumb: '/static/images/givenchy/options/Dress/Skirt/Skirt_5.webp',
			modelFile: '/static/models/givenchy/options/Dress/Skirt/Skirt_5.glb',
			blockName: 'Skirt 5',
			avatar: 'female',
			category: 'Skirt',
			collection: 'givenchy',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '22863b11-78cc-4535-add9-776a63a032af',
			thumb: '/static/images/givenchy/options/Dress/Skirt/Skirt_4.webp',
			modelFile: '/static/models/givenchy/options/Dress/Skirt/Skirt_4.glb',
			blockName: 'Skirt 4',
			avatar: 'female',
			category: 'Skirt',
			collection: 'givenchy',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '54612caf-5e08-444c-8da8-5c1fbd2528f5',
			thumb: '/static/images/givenchy/options/Dress/Skirt/Skirt_3.webp',
			modelFile: '/static/models/givenchy/options/Dress/Skirt/Skirt_3.glb',
			blockName: 'Skirt 3',
			avatar: 'female',
			category: 'Skirt',
			collection: 'givenchy',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '76b6f13a-166b-477e-b8d7-5ec4c0ad1a9f',
			thumb: '/static/images/givenchy/options/Dress/Skirt/Skirt_2.webp',
			modelFile: '/static/models/givenchy/options/Dress/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'givenchy',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '969765bf-598c-4e2c-9c6f-fe834addedc2',
			thumb: '/static/images/givenchy/options/Dress/Skirt/Skirt_1.webp',
			modelFile: '/static/models/givenchy/options/Dress/Skirt/Skirt_1.glb',
			blockName: 'Skirt 1',
			avatar: 'female',
			category: 'Skirt',
			collection: 'givenchy',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	dico: [
		{
			_id: '1fde42db-35b0-48f7-ad1d-0eae1988da7d',
			thumb: '/static/images/dico/blocks/Pants/Item_1___Pants/pants_1826.webp',
			modelFile: '/static/models/dico/blocks/Pants/Item_1___Pants/pants_1826.glb',
			blockName: 'pants 1826',
			avatar: 'female',
			category: 'Pants',
			collection: 'dico',
			templateId: 'f8c88e49-1e0c-41c9-a411-e440fcf5c6a2',
			templateName: 'Item 1',
			templateCategory: 'Pants',
		},
		{
			_id: '3934a7e1-3d35-41bb-8151-c95aeac6be43',
			thumb: '/static/images/dico/blocks/Top/Dico_Fluffy_Print_T-Shirt_Blac__Sleeves/sleeves_1829-a_pose.webp',
			modelFile: '/static/models/dico/blocks/Top/Dico_Fluffy_Print_T-Shirt_Blac__Sleeves/sleeves_1829-a_pose.glb',
			blockName: 'sleeves 1829-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'dico',
			templateId: '8ea47753-5edd-4c28-a046-78373980b6b6',
			templateName: 'Dico Fluffy Print T',
			templateCategory: 'Top',
		},
		{
			_id: '7514d92b-8da8-4d95-ae90-2c47a373a78a',
			thumb: '/static/images/dico/blocks/Top/Dico_Fluffy_Print_T-Shirt_Blac__Bodice/bodice_1827-a_pose.webp',
			modelFile: '/static/models/dico/blocks/Top/Dico_Fluffy_Print_T-Shirt_Blac__Bodice/bodice_1827-a_pose.glb',
			blockName: 'bodice 1827-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'dico',
			templateId: '8ea47753-5edd-4c28-a046-78373980b6b6',
			templateName: 'Dico Fluffy Print T',
			templateCategory: 'Top',
		},
	],

	dottie: [
		{
			_id: '3f5951e0-1d3f-4642-a8df-02f6851688e5',
			thumb: '/static/images/dottie/blocks/Pants/Item_1_Pants/pants_1809-a_pose.webp',
			modelFile: '/static/models/dottie/blocks/Pants/Item_1_Pants/pants_1809-a_pose.glb',
			blockName: 'pants 1809-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'dottie',
			templateId: '41a61ceb-5b92-4375-88c2-a98bc33bae23',
			templateName: 'Item 1',
			templateCategory: 'Pants',
		},
		{
			_id: '57577783-7696-4dcf-b6c5-e62ed4c41f84',
			thumb: '/static/images/dottie/blocks/Top/Ruffled_Trim_Cami_Bodice/bodice_1808-a_pose.webp',
			modelFile: '/static/models/dottie/blocks/Top/Ruffled_Trim_Cami_Bodice/bodice_1808-a_pose.glb',
			blockName: 'bodice 1808-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'dottie',
			templateId: '3553d0e3-9d30-4328-870e-3ae5a11f3018',
			templateName: 'Ruffled Trim Cami',
			templateCategory: 'Top',
		},
	],

	edini: [
		{
			_id: '89b92fcf-619d-4d54-928f-fcc5f92fe86c',
			thumb: '/static/images/edini/blocks/Dress/D1641_Fullbody/fullbody_1887-a_pose.webp',
			modelFile: '/static/models/edini/blocks/Dress/D1641_Fullbody/fullbody_1887-a_pose.glb',
			blockName: 'fullbody 1887-a pose',
			avatar: 'female',
			category: 'Full Body',
			collection: 'edini',
			templateId: '38871b4e-9baa-48bc-b971-44030b715a29',
			templateName: 'D1641',
			templateCategory: 'Dress',
		},
	],

	'erroris.ltd': [
		{
			_id: 'ca502de8-26cb-4be0-aba1-dd4a122c03c3',
			thumb: '/static/images/erroris.ltd/blocks/Pants/GREY_CAPRI_Pants/pants_1850-a_pose.webp',
			modelFile: '/static/models/erroris.ltd/blocks/Pants/GREY_CAPRI_Pants/pants_1850-a_pose.glb',
			blockName: 'pants 1850-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'erroris.ltd',
			templateId: '2a32a40b-fd7c-4fd8-a971-adff3ae1f3c0',
			templateName: 'GREY CAPRI',
			templateCategory: 'Pants',
		},
		{
			_id: '1cf5da1a-d34e-4ff3-83eb-4e6f63356e8d',
			thumb: '/static/images/erroris.ltd/blocks/Top/LUE_BABYDOLL_Bodice/bodice_1849-a_pose.webp',
			modelFile: '/static/models/erroris.ltd/blocks/Top/LUE_BABYDOLL_Bodice/bodice_1849-a_pose.glb',
			blockName: 'bodice 1849-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'erroris.ltd',
			templateId: '0c58654d-a6d9-4bee-aa88-979931af5e6d',
			templateName: 'LUE BABYDOLL',
			templateCategory: 'Top',
		},
	],

	gola: [
		{
			_id: '47030315-4e2e-4cc0-8ec3-2da0eafd1a8b',
			thumb: '/static/images/gola/blocks/Dress/Item_1___Fullbody/fullbody_1833.webp',
			modelFile: '/static/models/gola/blocks/Dress/Item_1___Fullbody/fullbody_1833.glb',
			blockName: 'fullbody 1833',
			avatar: 'female',
			category: 'Full Body',
			collection: 'gola',
			templateId: '3340f1c9-0b0c-4b3c-aae8-486558a39655',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	h2b: [
		{
			_id: '5dca9564-e74a-4839-a281-97b4b64d55b2',
			thumb: '/static/images/h2b/blocks/Pants/Item_1___Pants/pants_1785.webp',
			modelFile: '/static/models/h2b/blocks/Pants/Item_1___Pants/pants_1785.glb',
			blockName: 'pants 1785',
			avatar: 'female',
			category: 'Pants',
			collection: 'h2b',
			templateId: '19dedeb6-5de8-4da2-ade0-882ad5510786',
			templateName: 'Item 1',
			templateCategory: 'Pants',
		},
		{
			_id: '9b40f383-9ffe-47eb-8787-298e7a23d925',
			thumb: '/static/images/h2b/blocks/Top/Item_1___Bodice/top_1786.webp',
			modelFile: '/static/models/h2b/blocks/Top/Item_1___Bodice/top_1786.glb',
			blockName: 'top 1786',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h2b',
			templateId: 'b4282c23-93e1-42ea-8c2d-9a844d70b551',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	'joie-des-roses': [
		{
			_id: '81c17d3c-c69d-49f9-8fdf-8fd5c80d49a7',
			thumb: '/static/images/joie-des-roses/blocks/Jacket/Ena_jacket___Bodice/shirt_1783.webp',
			modelFile: '/static/models/joie-des-roses/blocks/Jacket/Ena_jacket___Bodice/shirt_1783.glb',
			blockName: 'shirt 1783',
			avatar: 'female',
			category: 'Bodice',
			collection: 'joie-des-roses',
			templateId: '013245d3-eea0-413e-94f5-a87726ed1b1c',
			templateName: 'Ena jacket',
			templateCategory: 'Jacket',
		},
		{
			_id: 'a3222748-c589-4398-b1f3-1bb2a05a390f',
			thumb: '/static/images/joie-des-roses/blocks/Jacket/Ena_jacket___Sleeves/sleeve_1781.webp',
			modelFile: '/static/models/joie-des-roses/blocks/Jacket/Ena_jacket___Sleeves/sleeve_1781.glb',
			blockName: 'sleeve 1781',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '013245d3-eea0-413e-94f5-a87726ed1b1c',
			templateName: 'Ena jacket',
			templateCategory: 'Jacket',
		},
		{
			_id: 'a3560e4d-df6c-4e42-b17d-992d575ac9c0',
			thumb: '/static/images/joie-des-roses/blocks/Dress/Ena_dress___Skirt/skirt_1782.webp',
			modelFile: '/static/models/joie-des-roses/blocks/Dress/Ena_dress___Skirt/skirt_1782.glb',
			blockName: 'skirt 1782',
			avatar: 'female',
			category: 'Dress',
			collection: 'joie-des-roses',
			templateId: '1461fdf5-628a-4aab-8a6f-035e9934a4a8',
			templateName: 'Ena Dress',
			templateCategory: 'Dress',
		},
		{
			_id: '1be774ef-5963-4df9-8524-78528fc59253',
			thumb: '/static/images/joie-des-roses/blocks/Dress/Ena_dress___Bodice/bodice_1780.webp',
			modelFile: '/static/models/joie-des-roses/blocks/Dress/Ena_dress___Bodice/bodice_1780.glb',
			blockName: 'bodice 1780',
			avatar: 'female',
			category: 'Bodice',
			collection: 'joie-des-roses',
			templateId: '1461fdf5-628a-4aab-8a6f-035e9934a4a8',
			templateName: 'Ena Dress',
			templateCategory: 'Dress',
		},
		{
			_id: '610858d5-fc69-461d-a159-1b54648e8d7b',
			thumb: '/static/images/joie-des-roses/options/Dress/Skirt/Skirt_2.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'c118b591-5f14-4243-82f3-36cc5a569fb9',
			thumb: '/static/images/joie-des-roses/options/Dress/Skirt/Skirt_1.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Skirt/Skirt_1.glb',
			blockName: 'Skirt 1',
			avatar: 'female',
			category: 'Skirt',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '9ae5c8ba-0e87-4291-97ce-28d89863677c',
			thumb: '/static/images/joie-des-roses/options/Dress/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'dcc46ebe-b1aa-43f8-999a-09ced207b689',
			thumb: '/static/images/joie-des-roses/options/Dress/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'b4659947-4324-483d-9af2-e0782e8e7d28',
			thumb: '/static/images/joie-des-roses/options/Dress/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '101cb3c3-8c47-431a-bc31-20d0ce7dfb4c',
			thumb: '/static/images/joie-des-roses/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '656d1dbe-e45a-4bed-b14e-71f3dcb97e65',
			thumb: '/static/images/joie-des-roses/options/Dress/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/joie-des-roses/options/Dress/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'joie-des-roses',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'jubin-studio': [
		{
			_id: '7e17a528-9d4f-4db9-b19c-ef1331676144',
			thumb: '/static/images/jubin-studio/blocks/Dress/Item_1_Fullbody/fullbody_1834.webp',
			modelFile: '/static/models/jubin-studio/blocks/Dress/Item_1_Fullbody/fullbody_1834.glb',
			blockName: 'fullbody 1834',
			avatar: 'female',
			category: 'Full Body',
			collection: 'jubin-studio',
			templateId: '2d9ba7a1-1037-4ceb-bcb4-da227220f974',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'celeste-studio': [
		{
			_id: '2c985b34-0b31-4937-bf38-53ccb5de1567',
			thumb: '/static/images/celeste-studio/blocks/Dress/RINA_DRESS_Sleeves/sleeves_1953.webp',
			modelFile: '/static/models/celeste-studio/blocks/Dress/RINA_DRESS_Sleeves/sleeves_1953.glb',
			blockName: 'sleeves 1953',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '88e0452f-3c2b-4c89-9029-8a4361ec010f',
			templateName: 'RINA DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: '1edbbb7b-1926-49e0-b881-8f8775487753',
			thumb: '/static/images/celeste-studio/blocks/Dress/RINA_DRESS_Fullbody/fullbody_1952.webp',
			modelFile: '/static/models/celeste-studio/blocks/Dress/RINA_DRESS_Fullbody/fullbody_1952.glb',
			blockName: 'fullbody 1952',
			avatar: 'female',
			category: 'Dress',
			collection: 'celeste-studio',
			templateId: '88e0452f-3c2b-4c89-9029-8a4361ec010f',
			templateName: 'RINA DRESS',
			templateCategory: 'Dress',
		},
		{
			_id: 'c33c2146-21f0-4338-8b2a-d5e30c704929',
			thumb: '/static/images/celeste-studio/options/Dress/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/celeste-studio/options/Dress/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'd9996231-ad3b-4479-850e-c715ce471033',
			thumb: '/static/images/celeste-studio/options/Dress/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/celeste-studio/options/Dress/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '5e6795da-b6a3-481e-9bef-8d7578b955ce',
			thumb: '/static/images/celeste-studio/options/Dress/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/celeste-studio/options/Dress/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'fa4b8cad-e5d6-4b47-a9a6-e0578455f179',
			thumb: '/static/images/celeste-studio/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/celeste-studio/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '227beb49-070c-496a-88b1-9d636ff263e5',
			thumb: '/static/images/celeste-studio/options/Dress/Sleeves/_Sleeves_1.webp',
			modelFile: '/static/models/celeste-studio/options/Dress/Sleeves/_Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celeste-studio',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'just-etro-gang': [
		{
			_id: '9de3a87a-6fab-4a13-8979-7483da46a196',
			thumb: '/static/images/just-etro-gang/blocks/Skirt/Rogue_Knit_set_Skirt/skirt_1891-a_pose.webp',
			modelFile: '/static/models/just-etro-gang/blocks/Skirt/Rogue_Knit_set_Skirt/skirt_1891-a_pose.glb',
			blockName: 'skirt 1891-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'just-etro-gang',
			templateId: 'ddea397d-c2ed-4be6-9af6-07547e294388',
			templateName: 'Rogue Knit set',
			templateCategory: 'Skirt',
		},
		{
			_id: '8a2ef1b7-1394-45f3-8871-5f1c2228f947',
			thumb: '/static/images/just-etro-gang/blocks/Top/Rogue_Knit_set_Sleeves/sleeves_1890-a_pose.webp',
			modelFile: '/static/models/just-etro-gang/blocks/Top/Rogue_Knit_set_Sleeves/sleeves_1890-a_pose.glb',
			blockName: 'sleeves 1890-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'just-etro-gang',
			templateId: '1b581b47-1f12-458b-8eac-55560ca58958',
			templateName: 'Rogue Knit set',
			templateCategory: 'Top',
		},
		{
			_id: '623bc05a-6bd5-43ea-bfbc-0464c515363b',
			thumb: '/static/images/just-etro-gang/blocks/Top/Rogue_Knit_set_Bodice/bodice_1889-a_pose.webp',
			modelFile: '/static/models/just-etro-gang/blocks/Top/Rogue_Knit_set_Bodice/bodice_1889-a_pose.glb',
			blockName: 'bodice 1889-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'just-etro-gang',
			templateId: '1b581b47-1f12-458b-8eac-55560ca58958',
			templateName: 'Rogue Knit set',
			templateCategory: 'Top',
		},
	],

	kido: [
		{
			_id: 'b2f6087d-c40f-4b5d-bd38-e7f967de3179',
			thumb: '/static/images/kido/blocks/Top/Item_1_Bodice/top_1832.webp',
			modelFile: '/static/models/kido/blocks/Top/Item_1_Bodice/top_1832.glb',
			blockName: 'top 1832',
			avatar: 'female',
			category: 'Bodice',
			collection: 'kido',
			templateId: 'c870b176-bd9e-4e00-a8e0-c2af5aab165e',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
		{
			_id: '057c748d-ef71-4f16-9247-e81976d3dd6c',
			thumb: '/static/images/kido/blocks/Top/Item_1_Sleeves/sleeve_1831.webp',
			modelFile: '/static/models/kido/blocks/Top/Item_1_Sleeves/sleeve_1831.glb',
			blockName: 'sleeve 1831',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'kido',
			templateId: 'c870b176-bd9e-4e00-a8e0-c2af5aab165e',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	levents: [
		{
			_id: '9ac58bf8-dd08-4aea-be39-0909adcf3114',
			thumb: '/static/images/levents/blocks/Top/Item_1_Sleeves/sleeves_1819-a_pose.webp',
			modelFile: '/static/models/levents/blocks/Top/Item_1_Sleeves/sleeves_1819-a_pose.glb',
			blockName: 'sleeves 1819-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'levents',
			templateId: 'a41cd95f-9fed-4461-9c07-9dad8d80ce63',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
		{
			_id: '6a950d4b-4df9-426f-afa3-7f2489ab34ec',
			thumb: '/static/images/levents/blocks/Top/Item_1_Bodice/bodice_1817-a_pose.webp',
			modelFile: '/static/models/levents/blocks/Top/Item_1_Bodice/bodice_1817-a_pose.glb',
			blockName: 'bodice 1817-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'levents',
			templateId: 'a41cd95f-9fed-4461-9c07-9dad8d80ce63',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
		{
			_id: 'e47162c1-8f1c-4a47-9e65-531201ad8ea4',
			thumb: '/static/images/levents/blocks/Skirt/Item_1_Skirt/skirt__1815-a_pose.webp',
			modelFile: '/static/models/levents/blocks/Skirt/Item_1_Skirt/skirt__1815-a_pose.glb',
			blockName: 'skirt 1815-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '6abb18f5-b435-4119-9d74-b52af4854f7b',
			templateName: 'Item 1',
			templateCategory: 'Skirt',
		},
		{
			_id: 'eeb14179-6bf7-4c54-a68a-e7b1f0f45314',
			thumb: '/static/images/levents/options/Skirt/Skirt/Skirt_5.webp',
			modelFile: '/static/models/levents/options/Skirt/Skirt/Skirt_5.glb',
			blockName: 'Skirt 5',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: '4eb7705f-e46f-4a09-95a2-74b7bf09c1bb',
			thumb: '/static/images/levents/options/Skirt/Skirt/Skirt_4.webp',
			modelFile: '/static/models/levents/options/Skirt/Skirt/Skirt_4.glb',
			blockName: 'Skirt 4',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: 'ba9f1356-8e5b-4b5f-b1cc-e8b2dac38e7a',
			thumb: '/static/images/levents/options/Skirt/Skirt/Skirt_3.webp',
			modelFile: '/static/models/levents/options/Skirt/Skirt/Skirt_3.glb',
			blockName: 'Skirt 3',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: 'b2d91398-6f5f-4917-ad88-94c11a0301cf',
			thumb: '/static/images/levents/options/Skirt/Skirt/Skirt_2.webp',
			modelFile: '/static/models/levents/options/Skirt/Skirt/Skirt_2.glb',
			blockName: 'Skirt 2',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: '09315974-a575-49df-8665-fa894dbb4d05',
			thumb: '/static/images/levents/options/Skirt/Skirt/Skirt_1.webp',
			modelFile: '/static/models/levents/options/Skirt/Skirt/Skirt_1.glb',
			blockName: 'Skirt 1',
			avatar: 'female',
			category: 'Skirt',
			collection: 'levents',
			templateId: '',
			templateName: '',
			templateCategory: 'Skirt',
		},
		{
			_id: '59b433d7-75b0-4b7a-9a9b-494d868a0632',
			thumb: '/static/images/levents/blocks/Jacket/SMALL_KNIT_CARDIGAN_Sleeves/sleeves_1818-a_pose.webp',
			modelFile: '/static/models/levents/blocks/Jacket/SMALL_KNIT_CARDIGAN_Sleeves/sleeves_1818-a_pose.glb',
			blockName: 'sleeves 1818-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'levents',
			templateId: 'b34d9893-24f2-42cc-a0b7-ddc33d3648d5',
			templateName: 'SMALL KNIT CARDIGAN',
			templateCategory: 'Jacket',
		},
		{
			_id: '1bd0ed92-5855-4095-8642-f3e95e26da82',
			thumb: '/static/images/levents/blocks/Jacket/SMALL_KNIT_CARDIGAN_Bodice/bodice_1816-a_pose.webp',
			modelFile: '/static/models/levents/blocks/Jacket/SMALL_KNIT_CARDIGAN_Bodice/bodice_1816-a_pose.glb',
			blockName: 'bodice 1816-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'levents',
			templateId: 'b34d9893-24f2-42cc-a0b7-ddc33d3648d5',
			templateName: 'SMALL KNIT CARDIGAN',
			templateCategory: 'Jacket',
		},
	],

	'bad-habits': [
		{
			_id: 'd6b44a5c-4d18-41fe-8f82-ab1a6f98a221',
			thumb: '/static/images/bad-habits/blocks/Top/INFO_TEE_Sleeves/sleeves_1840.webp',
			modelFile: '/static/models/bad-habits/blocks/Top/INFO_TEE_Sleeves/sleeves_1840.glb',
			blockName: 'sleeves 1840',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'bad-habits',
			templateId: '727a2789-d77a-400d-bb08-f0068261c06f',
			templateName: 'INFO TEE',
			templateCategory: 'Top',
		},
		{
			_id: 'c5fad9e7-e846-4a03-9cf6-bacc95c88dd4',
			thumb: '/static/images/bad-habits/blocks/Top/INFO_TEE_Bodice/bodice_1838.webp',
			modelFile: '/static/models/bad-habits/blocks/Top/INFO_TEE_Bodice/bodice_1838.glb',
			blockName: 'bodice 1838',
			avatar: 'female',
			category: 'Bodice',
			collection: 'bad-habits',
			templateId: '727a2789-d77a-400d-bb08-f0068261c06f',
			templateName: 'INFO TEE',
			templateCategory: 'Top',
		},
		{
			_id: 'd0fec71e-03e1-47ca-b2a4-4353d2ee6fca',
			thumb: '/static/images/bad-habits/blocks/Pants/Item_1_Pants/pants_1839.webp',
			modelFile: '/static/models/bad-habits/blocks/Pants/Item_1_Pants/pants_1839.glb',
			blockName: 'pants 1839',
			avatar: 'female',
			category: 'Pants',
			collection: 'bad-habits',
			templateId: 'ba919bc6-4086-480a-bbd7-aa419dc17f6f',
			templateName: 'Item 1',
			templateCategory: 'Pants',
		},
	],

	'beachclub.official': [
		{
			_id: '4c37c23f-eb04-4703-9eef-16f1e0fa290f',
			thumb: '/static/images/beachclub.official/blocks/Skirt/Delila_Set_Skirt/skirt_1866-a_pose.webp',
			modelFile: '/static/models/beachclub.official/blocks/Skirt/Delila_Set_Skirt/skirt_1866-a_pose.glb',
			blockName: 'skirt 1866-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'beachclub.official',
			templateId: '8e169f7a-a641-4390-bcd5-2e2de789dcf7',
			templateName: 'Delila Set',
			templateCategory: 'Skirt',
		},
		{
			_id: '58217aed-3dbc-45a2-815a-6b124098ef55',
			thumb: '/static/images/beachclub.official/blocks/Top/Delila_Set_Bodice/bodice_1865-a_pose.webp',
			modelFile: '/static/models/beachclub.official/blocks/Top/Delila_Set_Bodice/bodice_1865-a_pose.glb',
			blockName: 'bodice 1865-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'beachclub.official',
			templateId: 'c92614a3-ab50-429b-b201-04c2799ba9ae',
			templateName: 'Delila Set',
			templateCategory: 'Top',
		},
		{
			_id: '62b15e9d-236e-4e83-aa57-763ac15123f0',
			thumb: '/static/images/beachclub.official/options/Top/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/beachclub.official/options/Top/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'beachclub.official',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '4999bd57-dd48-4b7c-82be-b31e06cebedb',
			thumb: '/static/images/beachclub.official/options/Top/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/beachclub.official/options/Top/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'beachclub.official',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '10265cf7-cdcf-49ab-a1ee-7c68c24af652',
			thumb: '/static/images/beachclub.official/options/Top/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/beachclub.official/options/Top/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'beachclub.official',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'ffb0d542-6075-4119-abd1-f7a924eaf966',
			thumb: '/static/images/beachclub.official/options/Top/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/beachclub.official/options/Top/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'beachclub.official',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'cd9a377e-efda-49a8-b19a-0cadbe5ea22c',
			thumb: '/static/images/beachclub.official/options/Top/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/beachclub.official/options/Top/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'beachclub.official',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
	],

	berta: [
		{
			_id: 'd5be76ba-41d1-43bb-a9be-7c9dbfd01d52',
			thumb: '/static/images/berta/blocks/Dress/Item_1___Sleeves/sleeves_1938.webp',
			modelFile: '/static/models/berta/blocks/Dress/Item_1___Sleeves/sleeves_1938.glb',
			blockName: 'sleeves 1938',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'berta',
			templateId: '68c4697d-0fee-419a-b1a6-2120f78f3177',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
		{
			_id: '2863a88b-bb0e-407f-bfb9-3f703ef84b45',
			thumb: '/static/images/berta/blocks/Dress/Item_1___Fullbody/full_body_1937.webp',
			modelFile: '/static/models/berta/blocks/Dress/Item_1___Fullbody/full_body_1937.glb',
			blockName: 'full body 1937',
			avatar: 'female',
			category: 'Full Body',
			collection: 'berta',
			templateId: '68c4697d-0fee-419a-b1a6-2120f78f3177',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'cara-club': [
		{
			_id: 'cb477628-8a27-4fd7-abe4-ff73b0f1f11d',
			thumb: '/static/images/cara-club/blocks/Dress/Item_1_Fullbody/fullbody_1872-a_pose.webp',
			modelFile: '/static/models/cara-club/blocks/Dress/Item_1_Fullbody/fullbody_1872-a_pose.glb',
			blockName: 'fullbody 1872-a pose',
			avatar: 'female',
			category: 'Full Body',
			collection: 'cara-club',
			templateId: '0c64366d-c971-458f-af47-44d595102a0e',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
		{
			_id: 'a7609a08-bc5a-4471-a69a-646e8820a683',
			thumb: '/static/images/cara-club/options/Dress/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/cara-club/options/Dress/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'cara-club',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '1b50f39b-f050-45f5-9226-3a7d79b2fb06',
			thumb: '/static/images/cara-club/options/Dress/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/cara-club/options/Dress/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'cara-club',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'a7b160aa-844d-4ad9-af7b-f930d2278fdc',
			thumb: '/static/images/cara-club/options/Dress/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/cara-club/options/Dress/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'cara-club',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'e8f1a457-4b23-484b-b7f6-3cc6ae146360',
			thumb: '/static/images/cara-club/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/cara-club/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'cara-club',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'ce6058df-7f9d-4291-87dc-7de4d535ab3a',
			thumb: '/static/images/cara-club/options/Dress/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/cara-club/options/Dress/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'cara-club',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'ceci-cela': [
		{
			_id: '22d484b6-ad9a-4736-b5a8-f029ad0e89c8',
			thumb: '/static/images/ceci-cela/blocks/Dress/Item_1_Fullbody/fullbody_1904-a_pose.webp',
			modelFile: '/static/models/ceci-cela/blocks/Dress/Item_1_Fullbody/fullbody_1904-a_pose.glb',
			blockName: 'fullbody 1904-a pose',
			avatar: 'female',
			category: 'Full Body',
			collection: 'ceci-cela',
			templateId: '64f24b15-7e7a-469b-97be-2d0c6a473b51',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	celine: [
		{
			_id: '1f3845b9-4c9b-4e1f-85cb-3d4a3f1fdbc5',
			thumb: '/static/images/celine/blocks/Dress/Dress_IN_acetate_silk_crepe_Sleeves/sleeves_1936.webp',
			modelFile: '/static/models/celine/blocks/Dress/Dress_IN_acetate_silk_crepe_Sleeves/sleeves_1936.glb',
			blockName: 'sleeves 1936',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'celine',
			templateId: '9f752df5-e115-4d42-b1c3-eaf4b0000fac',
			templateName: 'Dress IN acetate silk crepe',
			templateCategory: 'Dress',
		},
		{
			_id: 'd2022eca-036a-404f-9fe0-5882ab436d02',
			thumb: '/static/images/celine/blocks/Dress/Dress_IN_acetate_silk_crepe_Fullbody/fullbody_1935.webp',
			modelFile: '/static/models/celine/blocks/Dress/Dress_IN_acetate_silk_crepe_Fullbody/fullbody_1935.glb',
			blockName: 'fullbody 1935',
			avatar: 'female',
			category: 'Dress',
			collection: 'celine',
			templateId: '9f752df5-e115-4d42-b1c3-eaf4b0000fac',
			templateName: 'Dress IN acetate silk crepe',
			templateCategory: 'Dress',
		},
	],

	colin: [
		{
			_id: '80a12a43-a43c-45c2-bc19-dfdd7700e9f5',
			thumb: '/static/images/colin/blocks/Dress/SET_REN_VAI_DAY_HOA_Skirt/skirt_1897-a_pose.webp',
			modelFile: '/static/models/colin/blocks/Dress/SET_REN_VAI_DAY_HOA_Skirt/skirt_1897-a_pose.glb',
			blockName: 'skirt 1897-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'colin',
			templateId: '7ff379c8-abee-47b4-aa6b-dd52ace1c121',
			templateName: 'SET REN VAI DAY HOA',
			templateCategory: 'Dress',
		},
		{
			_id: '663d5dc7-15bc-472c-85e9-98c0f569a4ff',
			thumb: '/static/images/colin/blocks/Dress/SET_REN_VAI_DAY_HOA_Bodice/bodice_1896-a_pose.webp',
			modelFile: '/static/models/colin/blocks/Dress/SET_REN_VAI_DAY_HOA_Bodice/bodice_1896-a_pose.glb',
			blockName: 'bodice 1896-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'colin',
			templateId: '7ff379c8-abee-47b4-aa6b-dd52ace1c121',
			templateName: 'SET REN VAI DAY HOA',
			templateCategory: 'Dress',
		},
		{
			_id: 'a0e76621-21d1-47b0-ad9a-aa2bc32fb3f2',
			thumb: '/static/images/colin/options/Dress/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/colin/options/Dress/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'colin',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '2d804db5-8e3d-4831-b50c-9e27a3279f06',
			thumb: '/static/images/colin/options/Dress/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/colin/options/Dress/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'colin',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'b8a9277d-6291-40fa-9b48-53d6ead75cce',
			thumb: '/static/images/colin/options/Dress/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/colin/options/Dress/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'colin',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '1bc108e6-acfb-4a05-8cea-579e6edba087',
			thumb: '/static/images/colin/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/colin/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'colin',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '4a04d207-6e9d-4372-ad2c-e1cc9128df9f',
			thumb: '/static/images/colin/options/Dress/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/colin/options/Dress/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'colin',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	demobaza: [
		{
			_id: '8c5b92cd-ffac-437a-ab64-d9dce4922542',
			thumb: '/static/images/demobaza/blocks/Dress/DRESS_ARISE_Sleeves/sleeves_1885-a_pose.webp',
			modelFile: '/static/models/demobaza/blocks/Dress/DRESS_ARISE_Sleeves/sleeves_1885-a_pose.glb',
			blockName: 'sleeves 1885-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '1638cfd4-7b30-4f68-ba47-c16ac9b87d56',
			templateName: 'DRESS ARISE',
			templateCategory: 'Dress',
		},
		{
			_id: '3322ed7d-6954-4ac7-ada0-ac8f616f1616',
			thumb: '/static/images/demobaza/blocks/Dress/DRESS_ARISE_Fullbody/fullbody_1886-a_pose.webp',
			modelFile: '/static/models/demobaza/blocks/Dress/DRESS_ARISE_Fullbody/fullbody_1886-a_pose.glb',
			blockName: 'fullbody 1886-a pose',
			avatar: 'female',
			category: 'Dress',
			collection: 'demobaza',
			templateId: '1638cfd4-7b30-4f68-ba47-c16ac9b87d56',
			templateName: 'DRESS ARISE',
			templateCategory: 'Dress',
		},
		{
			_id: '4c502eb9-539e-462b-9a1a-954e3f5bde61',
			thumb: '/static/images/demobaza/options/Dress/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/demobaza/options/Dress/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '7c0ed1da-cc40-4c0d-9f53-ba9252960ac8',
			thumb: '/static/images/demobaza/options/Dress/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/demobaza/options/Dress/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: 'dca89190-c1b5-431e-901b-6481514a9f34',
			thumb: '/static/images/demobaza/options/Dress/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/demobaza/options/Dress/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '69b37768-a08a-4c04-ab7a-945d909a9ae8',
			thumb: '/static/images/demobaza/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/demobaza/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '6a81a7d4-4cb2-4126-a068-f4cfefb2d9ac',
			thumb: '/static/images/demobaza/options/Dress/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/demobaza/options/Dress/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '9a44b759-f8cc-4c0f-a0b9-2fc665602529',
			thumb: '/static/images/demobaza/blocks/Dress/DRESS_REVERSE_Sleeves/sleeves_1861-a_pose.webp',
			modelFile: '/static/models/demobaza/blocks/Dress/DRESS_REVERSE_Sleeves/sleeves_1861-a_pose.glb',
			blockName: 'sleeves 1861-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'demobaza',
			templateId: '7909e2fd-f5f4-4d2b-8913-4a5b9eb45e56',
			templateName: 'DRESS REVERSE',
			templateCategory: 'Dress',
		},
		{
			_id: '073100f2-7e6d-4403-bf37-8e9a637e88b7',
			thumb: '/static/images/demobaza/blocks/Dress/DRESS_REVERSE_Bodice/fullbody_1860-a_pose.webp',
			modelFile: '/static/models/demobaza/blocks/Dress/DRESS_REVERSE_Bodice/fullbody_1860-a_pose.glb',
			blockName: 'fullbody 1860-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'demobaza',
			templateId: '7909e2fd-f5f4-4d2b-8913-4a5b9eb45e56',
			templateName: 'DRESS REVERSE',
			templateCategory: 'Dress',
		},
	],

	diane: [
		{
			_id: '92a60769-62e9-4b93-bd9b-4c6e078d7e16',
			thumb: '/static/images/diane/blocks/Skirt/APHRODITE_-_POMME_Skirt/skirt_1757.webp',
			modelFile: '/static/models/diane/blocks/Skirt/APHRODITE_-_POMME_Skirt/skirt_1757.glb',
			blockName: 'skirt 1757',
			avatar: 'female',
			category: 'Skirt',
			collection: 'diane',
			templateId: '02802552-a70d-41cb-a815-20d2192ca9e8',
			templateName: 'APHRODITE',
			templateCategory: 'Skirt',
		},
		{
			_id: '455db927-69e0-424e-9594-9e85b4c4a328',
			thumb: '/static/images/diane/blocks/Top/AMOUR_-_POMME___Sleeves/sleeve_1746.webp',
			modelFile: '/static/models/diane/blocks/Top/AMOUR_-_POMME___Sleeves/sleeve_1746.glb',
			blockName: 'sleeve 1746',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'diane',
			templateId: 'b77a41ef-b230-459c-86d9-0b65e07b1bad',
			templateName: 'AMOUR',
			templateCategory: 'Top',
		},
		{
			_id: '0a9ffbec-5256-4019-8bfe-007abf9b45bc',
			thumb: '/static/images/diane/blocks/Top/AMOUR_-_POMME___Bodice/bodice_1924.webp',
			modelFile: '/static/models/diane/blocks/Top/AMOUR_-_POMME___Bodice/bodice_1924.glb',
			blockName: 'bodice 1924',
			avatar: 'female',
			category: 'Bodice',
			collection: 'diane',
			templateId: 'b77a41ef-b230-459c-86d9-0b65e07b1bad',
			templateName: 'AMOUR',
			templateCategory: 'Top',
		},
		{
			_id: '20f91d2e-086a-49a8-9a59-f0b45ab51de2',
			thumb: '/static/images/diane/blocks/Dress/H%C3%89M%C3%89RA_-_FUCHSIA___Fullbody/fullbody_1745.webp',
			modelFile: '/static/models/diane/blocks/Dress/H%C3%89M%C3%89RA_-_FUCHSIA___Fullbody/fullbody_1745.glb',
			blockName: 'fullbody 1745',
			avatar: 'female',
			category: 'Full Body',
			collection: 'diane',
			templateId: 'bc52caf2-be6c-4bba-ac4a-d7ab38063808',
			templateName: 'HÉMÉRA',
			templateCategory: 'Dress',
		},
		{
			_id: 'a3b78cfa-ce47-474c-b9e5-0f76ee86ba1b',
			thumb: '/static/images/diane/blocks/Dress/H%C3%89M%C3%89RA_-_FUCHSIA___Sleeves/sleeve_1746.webp',
			modelFile: '/static/models/diane/blocks/Dress/H%C3%89M%C3%89RA_-_FUCHSIA___Sleeves/sleeve_1746.glb',
			blockName: 'sleeve 1746',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'diane',
			templateId: 'bc52caf2-be6c-4bba-ac4a-d7ab38063808',
			templateName: 'HÉMÉRA',
			templateCategory: 'Dress',
		},
	],

	hani: [
		{
			_id: 'dc123085-ee96-4835-abcd-31c285e944d0',
			thumb: '/static/images/hani/blocks/Dress/Item_1_Skirt/skirt_1867.webp',
			modelFile: '/static/models/hani/blocks/Dress/Item_1_Skirt/skirt_1867.glb',
			blockName: 'skirt 1867',
			avatar: 'female',
			category: 'Skirt',
			collection: 'hani',
			templateId: '529c419f-77ab-4f95-9aa3-cf60ce4af7d3',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
		{
			_id: '7e7279e7-0283-4af5-bb3b-f95014234556',
			thumb: '/static/images/hani/blocks/Dress/Item_1_Bodice/bodice_1869.webp',
			modelFile: '/static/models/hani/blocks/Dress/Item_1_Bodice/bodice_1869.glb',
			blockName: 'bodice 1869',
			avatar: 'female',
			category: 'Bodice',
			collection: 'hani',
			templateId: '529c419f-77ab-4f95-9aa3-cf60ce4af7d3',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'huelley-rose': [
		{
			_id: '638aee65-bc2d-43f0-8b15-42dd8ebd563d',
			thumb: '/static/images/huelley-rose/blocks/Dress/Item_1_Fullbody/fullbody_1864.webp',
			modelFile: '/static/models/huelley-rose/blocks/Dress/Item_1_Fullbody/fullbody_1864.glb',
			blockName: 'fullbody 1864',
			avatar: 'female',
			category: 'Full Body',
			collection: 'huelley-rose',
			templateId: '002f42dc-9a26-4061-b21d-9e8560e1e73d',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'hurricane-b': [
		{
			_id: '92a20587-ca0c-4af0-8cc9-de4904f80403',
			thumb: '/static/images/hurricane-b/blocks/Dress/Abito_lungo_con_cut_out_Fullbody/fullbody_1879-a_pose.webp',
			modelFile: '/static/models/hurricane-b/blocks/Dress/Abito_lungo_con_cut_out_Fullbody/fullbody_1879-a_pose.glb',
			blockName: 'fullbody 1879-a pose',
			avatar: 'female',
			category: 'Full Body',
			collection: 'hurricane-b',
			templateId: '4a59fc25-20f0-4e29-a331-2d6852bb07e8',
			templateName: 'Abito lungo con cut out',
			templateCategory: 'Dress',
		},
		{
			_id: '03837a90-2d11-403d-884f-a951808cc207',
			thumb: '/static/images/hurricane-b/options/Dress/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/hurricane-b/options/Dress/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'hurricane-b',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
		{
			_id: '7161b007-b2a5-4387-85ae-8b8c8fc5adc8',
			thumb: '/static/images/hurricane-b/options/Dress/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/hurricane-b/options/Dress/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'hurricane-b',
			templateId: '',
			templateName: '',
			templateCategory: 'Dress',
		},
	],

	'fig.cool-leather': [
		{
			_id: 'c5928fe3-ef5a-4615-b586-1abf6bc06f58',
			thumb: '/static/images/fig.cool-leather/blocks/Skirt/Saia_de_Couro_Adele_Skirt/skirt_1871-a_pose.webp',
			modelFile: '/static/models/fig.cool-leather/blocks/Skirt/Saia_de_Couro_Adele_Skirt/skirt_1871-a_pose.glb',
			blockName: 'skirt 1871-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'fig.cool-leather',
			templateId: '3a0eaf89-a600-4823-adc5-670ba0377995',
			templateName: 'Saia de Couro Adele',
			templateCategory: 'Skirt',
		},
		{
			_id: '8b34574d-f8f5-42e3-b4af-59ca2ae2d6d4',
			thumb: '/static/images/fig.cool-leather/blocks/Top/Item_1_Bodice/bodice_1870-a_pose.webp',
			modelFile: '/static/models/fig.cool-leather/blocks/Top/Item_1_Bodice/bodice_1870-a_pose.glb',
			blockName: 'bodice 1870-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'fig.cool-leather',
			templateId: '9dd379b6-0b1f-4541-98ea-b30ff0a5b1bc',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	libeworkshop: [
		{
			_id: '9045073f-54c3-4a01-9238-cdfcffc8014e',
			thumb: '/static/images/libeworkshop/blocks/Skirt/Item_1_Skirt/skirts_1837-a_pose.webp',
			modelFile: '/static/models/libeworkshop/blocks/Skirt/Item_1_Skirt/skirts_1837-a_pose.glb',
			blockName: 'skirts 1837-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'libeworkshop',
			templateId: '1fc1b5c3-ec98-4efa-86d9-9843307b44da',
			templateName: 'Item 1',
			templateCategory: 'Skirt',
		},
		{
			_id: '1b5a844e-6e89-4c6b-bdf5-9b385f652a7e',
			thumb: '/static/images/libeworkshop/blocks/Top/Floral_Scoop_Neck_Drawstring_Top_Bodice/bodice_1877-a_pose.webp',
			modelFile:
				'/static/models/libeworkshop/blocks/Top/Floral_Scoop_Neck_Drawstring_Top_Bodice/bodice_1877-a_pose.glb',
			blockName: 'bodice 1877-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'libeworkshop',
			templateId: 'b10f11db-b2a1-4acf-a0f3-f4897b1b389c',
			templateName: 'Floral Scoop Neck Drawstring Top',
			templateCategory: 'Top',
		},
	],

	'liniss-official': [
		{
			_id: '06ee9a28-7776-44a7-bba4-c3be4558e216',
			thumb: '/static/images/liniss-official/blocks/Pants/ROSE_SET_Pants/pants_1884-a_pose.webp',
			modelFile: '/static/models/liniss-official/blocks/Pants/ROSE_SET_Pants/pants_1884-a_pose.glb',
			blockName: 'pants 1884-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'liniss-official',
			templateId: 'ad034a52-807f-43f4-b227-a9f61149d834',
			templateName: 'ROSE SET',
			templateCategory: 'Pants',
		},
		{
			_id: '2d447f9e-1f7b-436b-a1ce-5a973d6f3c2f',
			thumb: '/static/images/liniss-official/blocks/Top/ROSE_SET_Sleeves/sleeves_1883-a_pose.webp',
			modelFile: '/static/models/liniss-official/blocks/Top/ROSE_SET_Sleeves/sleeves_1883-a_pose.glb',
			blockName: 'sleeves 1883-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'liniss-official',
			templateId: 'e373d707-e738-4b12-b718-0eba503b07d1',
			templateName: 'ROSE SET',
			templateCategory: 'Top',
		},
		{
			_id: 'becb2325-f376-42b7-a359-d9e2276871fe',
			thumb: '/static/images/liniss-official/blocks/Top/ROSE_SET_Bodice/bodice_1882-a_pose.webp',
			modelFile: '/static/models/liniss-official/blocks/Top/ROSE_SET_Bodice/bodice_1882-a_pose.glb',
			blockName: 'bodice 1882-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'liniss-official',
			templateId: 'e373d707-e738-4b12-b718-0eba503b07d1',
			templateName: 'ROSE SET',
			templateCategory: 'Top',
		},
	],

	meanbldv: [
		{
			_id: 'c1169c2c-603f-479f-887d-18994c384e23',
			thumb: '/static/images/meanbldv/blocks/Dress/Islington_Mermaid_Ribbon_Maxi_Dress_Fullbody/fullbody_1955.webp',
			modelFile: '/static/models/meanbldv/blocks/Dress/Islington_Mermaid_Ribbon_Maxi_Dress_Fullbody/fullbody_1955.glb',
			blockName: 'fullbody 1955',
			avatar: 'female',
			category: 'Dress',
			collection: 'meanbldv',
			templateId: 'a994c271-0712-4953-9802-b2775928b562',
			templateName: 'Islington Mermaid Ribbon Maxi Dress',
			templateCategory: 'Dress',
		},
	],

	'milk-white': [
		{
			_id: '2a627b44-9607-4d8f-8067-f1227321ff85',
			thumb: '/static/images/milk-white/blocks/Pants/SHORTS_WITH_FLOWER_DETAIL_Pants/pants_1903-a_pose.webp',
			modelFile: '/static/models/milk-white/blocks/Pants/SHORTS_WITH_FLOWER_DETAIL_Pants/pants_1903-a_pose.glb',
			blockName: 'pants 1903-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'milk-white',
			templateId: '4d191893-1a62-42db-a075-ac892cefde5c',
			templateName: 'SHORTS WITH FLOWER DETAIL',
			templateCategory: 'Pants',
		},
		{
			_id: 'b3a32226-e639-4f52-aed3-15bef5bf9036',
			thumb: '/static/images/milk-white/blocks/Top/Item_1_Sleeves/sleeves_1902-a_pose.webp',
			modelFile: '/static/models/milk-white/blocks/Top/Item_1_Sleeves/sleeves_1902-a_pose.glb',
			blockName: 'sleeves 1902-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'milk-white',
			templateId: '2ced1a9d-240c-4e6d-a434-6f67f18beb7f',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
		{
			_id: '13937349-ba9d-433f-b916-8282800d3899',
			thumb: '/static/images/milk-white/blocks/Top/Item_1_Bodice/bodice_1901-a_pose.webp',
			modelFile: '/static/models/milk-white/blocks/Top/Item_1_Bodice/bodice_1901-a_pose.glb',
			blockName: 'bodice 1901-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'milk-white',
			templateId: '2ced1a9d-240c-4e6d-a434-6f67f18beb7f',
			templateName: 'Item 1',
			templateCategory: 'Top',
		},
	],

	'mono-talk': [
		{
			_id: 'f6aebc7f-bd96-4179-8262-729d44a74e0f',
			thumb: '/static/images/mono-talk/blocks/Top/MCS25W_Sleeves/sleeves_1857-a_pose.webp',
			modelFile: '/static/models/mono-talk/blocks/Top/MCS25W_Sleeves/sleeves_1857-a_pose.glb',
			blockName: 'sleeves 1857-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: 'f4a30f3f-57e9-479e-80db-dd35c15dbc6c',
			templateName: 'MCS25W',
			templateCategory: 'Top',
		},
		{
			_id: 'fcba4b95-a2ff-4b22-a7a6-9d70bddcdf0d',
			thumb: '/static/images/mono-talk/blocks/Top/MCS25W_Bodice/bodice_1856-a_pose.webp',
			modelFile: '/static/models/mono-talk/blocks/Top/MCS25W_Bodice/bodice_1856-a_pose.glb',
			blockName: 'bodice 1856-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'mono-talk',
			templateId: 'f4a30f3f-57e9-479e-80db-dd35c15dbc6c',
			templateName: 'MCS25W',
			templateCategory: 'Top',
		},
		{
			_id: '3b522070-3592-4639-ad9a-9f126a3b7896',
			thumb: '/static/images/mono-talk/options/Top/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/mono-talk/options/Top/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'a6803a04-561d-4d12-af81-fa8bc4ea0c1d',
			thumb: '/static/images/mono-talk/options/Top/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/mono-talk/options/Top/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'cd73d49d-491d-4587-963f-28e1aafab722',
			thumb: '/static/images/mono-talk/options/Top/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/mono-talk/options/Top/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '2c9df7cc-1346-49d6-906e-3b3dde76f8a7',
			thumb: '/static/images/mono-talk/options/Top/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/mono-talk/options/Top/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '042c752f-96ad-4578-a83c-ecdf5d9abc82',
			thumb: '/static/images/mono-talk/options/Top/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/mono-talk/options/Top/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'mono-talk',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'ae24e02c-62a0-4c7c-a997-786aba2975f9',
			thumb: '/static/images/mono-talk/blocks/Skirt/Item_1_Skirt/skirt_1858-a_pose.webp',
			modelFile: '/static/models/mono-talk/blocks/Skirt/Item_1_Skirt/skirt_1858-a_pose.glb',
			blockName: 'skirt 1858-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'mono-talk',
			templateId: '2b9efb05-8965-45dd-bb2d-552950a9d607',
			templateName: 'Item 1',
			templateCategory: 'Skirt',
		},
	],

	'monroe-the-label': [
		{
			_id: 'a326b077-28d9-43c5-a6c6-71f48f757fd5',
			thumb: '/static/images/monroe-the-label/blocks/Pants/JUNO_PANTS_Pants/pants_1772-a_pose.webp',
			modelFile: '/static/models/monroe-the-label/blocks/Pants/JUNO_PANTS_Pants/pants_1772-a_pose.glb',
			blockName: 'pants 1772-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'monroe-the-label',
			templateId: '7d1f6933-0c61-49e0-b452-c66a82b111e4',
			templateName: 'JUNO PANTS',
			templateCategory: 'Pants',
		},
		{
			_id: '54d07a5f-39cc-4adb-9f9a-1d100dabaa38',
			thumb: '/static/images/monroe-the-label/blocks/Top/SUKI_LONG_SLEEVE_Sleeves/sleeves_1771-a_pose.webp',
			modelFile: '/static/models/monroe-the-label/blocks/Top/SUKI_LONG_SLEEVE_Sleeves/sleeves_1771-a_pose.glb',
			blockName: 'sleeves 1771-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: 'b069115c-6cfb-4f10-b9f5-b3df4e83a30a',
			templateName: 'SUKI LONG SLEEVE',
			templateCategory: 'Top',
		},
		{
			_id: '5cdcd867-e697-4939-91db-8147779ba36f',
			thumb: '/static/images/monroe-the-label/blocks/Top/SUKI_LONG_SLEEVE_Bodice/bodice_1770-a_pose.webp',
			modelFile: '/static/models/monroe-the-label/blocks/Top/SUKI_LONG_SLEEVE_Bodice/bodice_1770-a_pose.glb',
			blockName: 'bodice 1770-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'monroe-the-label',
			templateId: 'b069115c-6cfb-4f10-b9f5-b3df4e83a30a',
			templateName: 'SUKI LONG SLEEVE',
			templateCategory: 'Top',
		},
		{
			_id: 'd169382d-9ca5-491c-a739-7c67bf437163',
			thumb: '/static/images/monroe-the-label/options/Top/Sleeves/Sleeves_5.webp',
			modelFile: '/static/models/monroe-the-label/options/Top/Sleeves/Sleeves_5.glb',
			blockName: 'Sleeves 5',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '1953051a-6186-4e53-bd11-b3084d6e038a',
			thumb: '/static/images/monroe-the-label/options/Top/Sleeves/Sleeves_4.webp',
			modelFile: '/static/models/monroe-the-label/options/Top/Sleeves/Sleeves_4.glb',
			blockName: 'Sleeves 4',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: 'a0da1823-f339-4e77-a67b-c2bb1a11dd52',
			thumb: '/static/images/monroe-the-label/options/Top/Sleeves/Sleeves_3.webp',
			modelFile: '/static/models/monroe-the-label/options/Top/Sleeves/Sleeves_3.glb',
			blockName: 'Sleeves 3',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '63e79161-3e72-4045-86d5-506c74926f7f',
			thumb: '/static/images/monroe-the-label/options/Top/Sleeves/Sleeves_2.webp',
			modelFile: '/static/models/monroe-the-label/options/Top/Sleeves/Sleeves_2.glb',
			blockName: 'Sleeves 2',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
		{
			_id: '1789ff96-1454-40a7-8ec9-0f5382b64cfe',
			thumb: '/static/images/monroe-the-label/options/Top/Sleeves/Sleeves_1.webp',
			modelFile: '/static/models/monroe-the-label/options/Top/Sleeves/Sleeves_1.glb',
			blockName: 'Sleeves 1',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'monroe-the-label',
			templateId: '',
			templateName: '',
			templateCategory: 'Top',
		},
	],

	naked: [
		{
			_id: 'eeef6348-218a-482b-9f89-5ea43c568ab9',
			thumb: '/static/images/naked/blocks/Skirt/Khu%C3%AA_%C4%90i%E1%BB%87p_Skirt/skirt_1854-a_pose.webp',
			modelFile: '/static/models/naked/blocks/Skirt/Khu%C3%AA_%C4%90i%E1%BB%87p_Skirt/skirt_1854-a_pose.glb',
			blockName: 'skirt 1854-a pose',
			avatar: 'female',
			category: 'Skirt',
			collection: 'naked',
			templateId: '12a030a9-6f53-48b8-87b3-4c3e4cd7734e',
			templateName: 'Khuê Điệp',
			templateCategory: 'Skirt',
		},
		{
			_id: '6e874d00-770d-458f-bb4e-360aa2b0a4a8',
			thumb: '/static/images/naked/blocks/Top/Khu%C3%AA_Di%E1%BB%87p_Sleeves/sleeves_1855-a_pose.webp',
			modelFile: '/static/models/naked/blocks/Top/Khu%C3%AA_Di%E1%BB%87p_Sleeves/sleeves_1855-a_pose.glb',
			blockName: 'sleeves 1855-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'naked',
			templateId: '4d1e9684-22f0-407a-8fd8-3d7b39734edd',
			templateName: 'Khuê Điệp',
			templateCategory: 'Top',
		},
		{
			_id: '735aff67-7b37-40b9-829e-9d280483d5ce',
			thumb: '/static/images/naked/blocks/Top/Khu%C3%AA_%C4%90i%E1%BB%87p_Bodice/bodice_1853-a_pose.webp',
			modelFile: '/static/models/naked/blocks/Top/Khu%C3%AA_%C4%90i%E1%BB%87p_Bodice/bodice_1853-a_pose.glb',
			blockName: 'bodice 1853-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'naked',
			templateId: '4d1e9684-22f0-407a-8fd8-3d7b39734edd',
			templateName: 'Khuê Điệp',
			templateCategory: 'Top',
		},
	],

	nakedandfamousdenim: [
		{
			_id: '2893f7e6-e690-4248-984a-607d0e5c68ea',
			thumb: '/static/images/nakedandfamousdenim/blocks/Top/Cropped_Denim_Jacket_Sleeves/sleeves_1928.webp',
			modelFile: '/static/models/nakedandfamousdenim/blocks/Top/Cropped_Denim_Jacket_Sleeves/sleeves_1928.glb',
			blockName: 'sleeves 1928',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'nakedandfamousdenim',
			templateId: 'b90777b2-55bb-4311-904f-631873399f23',
			templateName: 'Cropped Denim Jacket',
			templateCategory: 'Top',
		},
		{
			_id: '034c8ac0-d008-475c-9473-213e6a61a45e',
			thumb: '/static/images/nakedandfamousdenim/blocks/Top/Cropped_Denim_Jacket_Bodice/bodice_1926.webp',
			modelFile: '/static/models/nakedandfamousdenim/blocks/Top/Cropped_Denim_Jacket_Bodice/bodice_1926.glb',
			blockName: 'bodice 1926',
			avatar: 'female',
			category: 'Bodice',
			collection: 'nakedandfamousdenim',
			templateId: 'b90777b2-55bb-4311-904f-631873399f23',
			templateName: 'Cropped Denim Jacket',
			templateCategory: 'Top',
		},
		{
			_id: '26993899-d26d-46b0-9251-977bac5a532f',
			thumb: '/static/images/nakedandfamousdenim/blocks/Pants/Judo_Sashiko_Pants/pants_1927.webp',
			modelFile: '/static/models/nakedandfamousdenim/blocks/Pants/Judo_Sashiko_Pants/pants_1927.glb',
			blockName: 'pants 1927',
			avatar: 'female',
			category: 'Pants',
			collection: 'nakedandfamousdenim',
			templateId: 'b6be439b-66ae-4a6e-b338-b4934e5e1b1c',
			templateName: 'Judo Sashiko',
			templateCategory: 'Pants',
		},
	],

	'zd-eye-of-the-storm': [
		{
			_id: '3dca2ec5-7ed6-4faf-b411-13066661583d',
			thumb: '/static/images/zd-eye-of-the-storm/blocks/Top/JACKET_Sleeves/sleeves_1802-a_pose.webp',
			modelFile: '/static/models/zd-eye-of-the-storm/blocks/Top/JACKET_Sleeves/sleeves_1802-a_pose.glb',
			blockName: 'sleeves 1802-a pose',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'zd-eye-of-the-storm',
			templateId: '8211585d-d339-4366-963f-5e3ceebff247',
			templateName: 'JACKET',
			templateCategory: 'Top',
		},
		{
			_id: 'bd9429a2-aca0-428d-b503-79f1bec23f6d',
			thumb: '/static/images/zd-eye-of-the-storm/blocks/Top/JACKET_Bodice/bodice_1801-a_pose.webp',
			modelFile: '/static/models/zd-eye-of-the-storm/blocks/Top/JACKET_Bodice/bodice_1801-a_pose.glb',
			blockName: 'bodice 1801-a pose',
			avatar: 'female',
			category: 'Bodice',
			collection: 'zd-eye-of-the-storm',
			templateId: '8211585d-d339-4366-963f-5e3ceebff247',
			templateName: 'JACKET',
			templateCategory: 'Top',
		},
		{
			_id: '91c5a2a2-42ac-4af5-82d8-05cb42a428c6',
			thumb: '/static/images/zd-eye-of-the-storm/blocks/Pants/ARCHRISE_SHORTS_Pants/pants_1797-a_pose.webp',
			modelFile: '/static/models/zd-eye-of-the-storm/blocks/Pants/ARCHRISE_SHORTS_Pants/pants_1797-a_pose.glb',
			blockName: 'pants 1797-a pose',
			avatar: 'female',
			category: 'Pants',
			collection: 'zd-eye-of-the-storm',
			templateId: '8c0785b4-0819-4b05-a38b-a44b9c4ef39c',
			templateName: 'ARCHRISE SHORTS',
			templateCategory: 'Pants',
		},
	],

	metamorphosis: [
		{
			_id: '60cfcb27-547e-477d-89c8-1b870cd15f7e',
			thumb: '/static/images/metamorphosis/blocks/Accessories/Item_1_Accessory/accessory_1519.webp',
			modelFile: '/static/models/metamorphosis/blocks/Accessories/Item_1_Accessory/accessory_1519.glb',
			blockName: 'accessory 1519',
			avatar: 'female',
			category: 'Accessory',
			collection: 'metamorphosis',
			templateId: 'e127a26f-cef4-4253-a6ed-25a468199d31',
			templateName: 'Ava',
			templateCategory: 'Accessories',
		},
		{
			_id: '55080b36-fd9e-4295-b4bf-6cd5f9f1aad4',
			thumb: '/static/images/metamorphosis/blocks/Accessories/Item_2_Accessory/accessory_1586.webp',
			modelFile: '/static/models/metamorphosis/blocks/Accessories/Item_2_Accessory/accessory_1586.glb',
			blockName: 'accessory 1586',
			avatar: 'female',
			category: 'Accessory',
			collection: 'metamorphosis',
			templateId: 'a7d35b1c-22f2-4dd6-a75a-19b39ea755e2',
			templateName: 'Pli',
			templateCategory: 'Accessories',
		},
		{
			_id: '13ee6ed4-7038-4632-8ce2-17ba2439bf4c',
			thumb: '/static/images/metamorphosis/blocks/Dress/Item_1_Fullbody/fullbody_1517.webp',
			modelFile: '/static/models/metamorphosis/blocks/Dress/Item_1_Fullbody/fullbody_1517.glb',
			blockName: 'fullbody 1517',
			avatar: 'female',
			category: 'Full Body',
			collection: 'metamorphosis',
			templateId: '7629b681-5369-412f-83cb-e0673484e834',
			templateName: 'Severance',
			templateCategory: 'Dress',
		},
		{
			_id: '7c810a2d-1974-4937-96cd-5f030b3ce522',
			thumb: '/static/images/metamorphosis/blocks/Dress/Item_2_Fullbody/fullbody_1518.webp',
			modelFile: '/static/models/metamorphosis/blocks/Dress/Item_2_Fullbody/fullbody_1518.glb',
			blockName: 'fullbody 1518',
			avatar: 'female',
			category: 'Full Body',
			collection: 'metamorphosis',
			templateId: 'e73d2cc8-f45a-4660-9de3-a43d86e485f6',
			templateName: 'Item 2',
			templateCategory: 'Dress',
		},
		{
			_id: '365c10d4-32cd-4b0f-8869-875d2ed937f1',
			thumb: '/static/images/metamorphosis/blocks/Pants/Item_1___Pants/pants_1606.webp',
			modelFile: '/static/models/metamorphosis/blocks/Pants/Item_1___Pants/pants_1606.glb',
			blockName: 'pants 1606',
			avatar: 'female',
			category: 'Pants',
			collection: 'metamorphosis',
			templateId: 'a60efe32-5853-4935-b92a-a1d574eb9092',
			templateName: 'Liminal',
			templateCategory: 'Pants',
		},
		{
			_id: '4ac9cb49-6c20-4faf-aec2-3f26c57c6137',
			thumb: '/static/images/metamorphosis/blocks/Top/Item_2_Sleeves/sleeves_1581.webp',
			modelFile: '/static/models/metamorphosis/blocks/Top/Item_2_Sleeves/sleeves_1581.glb',
			blockName: 'sleeves 1581',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'metamorphosis',
			templateId: '20e12023-a26c-4da1-94bc-a7683fea8708',
			templateName: 'Whiteout',
			templateCategory: 'Top',
		},
		{
			_id: '9517708b-f938-4345-ad02-f6005a58aa2f',
			thumb: '/static/images/metamorphosis/blocks/Top/Item_1_Bodice/bodice_1580.webp',
			modelFile: '/static/models/metamorphosis/blocks/Top/Item_1_Bodice/bodice_1580.glb',
			blockName: 'bodice 1580',
			avatar: 'female',
			category: 'Bodice',
			collection: 'metamorphosis',
			templateId: '20e12023-a26c-4da1-94bc-a7683fea8708',
			templateName: 'Whiteout',
			templateCategory: 'Top',
		},
		{
			_id: '2ac4f5aa-aa0f-40f2-88c1-585b732d25b5',
			thumb: '/static/images/metamorphosis/blocks/Top/Item_3_Bodice/bodice_190.webp',
			modelFile: '/static/models/metamorphosis/blocks/Top/Item_3_Bodice/bodice_190.glb',
			blockName: 'bodice 190',
			avatar: 'female',
			category: 'Bodice',
			collection: 'metamorphosis',
			templateId: 'cf823967-86f4-4f66-9b5f-10d898fd9fb2',
			templateName: 'The Triad',
			templateCategory: 'Top',
		},
		{
			_id: '63f90b62-3ed5-4b87-a70c-caedb2c42181',
			thumb: '/static/images/metamorphosis/blocks/Top/Item_3_Sleeves/sleeves_190.webp',
			modelFile: '/static/models/metamorphosis/blocks/Top/Item_3_Sleeves/sleeves_190.glb',
			blockName: 'sleeves 190',
			avatar: 'female',
			category: 'Sleeves',
			collection: 'metamorphosis',
			templateId: 'cf823967-86f4-4f66-9b5f-10d898fd9fb2',
			templateName: 'The Triad',
			templateCategory: 'Top',
		},
		{
			_id: '2cba1904-9173-4764-bece-8c05eb1d5740',
			thumb: '/static/images/metamorphosis/blocks/Top/Item_2_Bodice/bodice_1585.webp',
			modelFile: '/static/models/metamorphosis/blocks/Top/Item_2_Bodice/bodice_1585.glb',
			blockName: 'bodice 1585',
			avatar: 'female',
			category: 'Bodice',
			collection: 'metamorphosis',
			templateId: '2eb802b0-940f-4914-8eb8-dbeb2eb192d8',
			templateName: 'Frame',
			templateCategory: 'Top',
		},
		{
			_id: '923172aa-dfcf-42e0-a6aa-7465c765e064',
			thumb: '/static/images/metamorphosis/blocks/Skirt/Item_1_Skirt/skirt_1584.webp',
			modelFile: '/static/models/metamorphosis/blocks/Skirt/Item_1_Skirt/skirt_1584.glb',
			blockName: 'skirt 1584',
			avatar: 'female',
			category: 'Skirt',
			collection: 'metamorphosis',
			templateId: '9450696d-310c-407f-aea3-a40f61081722',
			templateName: 'Lamella',
			templateCategory: 'Skirt',
		},
	],

	'h&m': [
		{
			_id: '48389db6-bcda-4046-a694-15e6b400075c',
			thumb: '/static/images/h%26m/blocks/Skirt/Flared_Skirt_Skirt/skirt_1920.webp',
			modelFile: '/static/models/h%26m/blocks/Skirt/Flared_Skirt_Skirt/skirt_1920.glb',
			blockName: 'skirt 1920',
			avatar: 'female',
			category: 'Skirt',
			collection: 'h&m',
			templateId: '8b24dc1a-b2ba-414b-87ee-6bb85df4c472',
			templateName: 'Flared Skirt',
			templateCategory: 'Skirt',
		},
		{
			_id: 'e4c07949-abb6-45b5-9424-e07dbbd1aa6b',
			thumb: '/static/images/h%26m/blocks/Skirt/Silk_satin_maxi_skirt_Skirt/skirt_1919.webp',
			modelFile: '/static/models/h%26m/blocks/Skirt/Silk_satin_maxi_skirt_Skirt/skirt_1919.glb',
			blockName: 'skirt 1919',
			avatar: 'female',
			category: 'Skirt',
			collection: 'h&m',
			templateId: '59a3c7a7-694c-4e3b-9c8e-649052a79bf4',
			templateName: 'Silk satin maxi skirt',
			templateCategory: 'Skirt',
		},
		{
			_id: 'fef35e2e-6ec0-4ef6-8439-a39d8c6ad245',
			thumb: '/static/images/h%26m/blocks/Skirt/Frilled_mini_skort_Skirt/skirt_1917.webp',
			modelFile: '/static/models/h%26m/blocks/Skirt/Frilled_mini_skort_Skirt/skirt_1917.glb',
			blockName: 'skirt 1917',
			avatar: 'female',
			category: 'Skirt',
			collection: 'h&m',
			templateId: '72dbbde8-ceb9-4d2c-ba99-8f4f3615243f',
			templateName: 'Frilled mini skort',
			templateCategory: 'Skirt',
		},
		{
			_id: '6e181ab3-7c5e-4ae2-9dfd-86e85bd17d20',
			thumb: '/static/images/h%26m/blocks/Dress/Mini_Dress_Fullbody/fullbody_1921.webp',
			modelFile: '/static/models/h%26m/blocks/Dress/Mini_Dress_Fullbody/fullbody_1921.glb',
			blockName: 'fullbody 1921',
			avatar: 'female',
			category: 'Dress',
			collection: 'h&m',
			templateId: '779ddb1a-e14c-4b51-a8ba-ffaf004c3df6',
			templateName: 'Mini Dress',
			templateCategory: 'Dress',
		},
		{
			_id: 'b6b0b2f8-f2cc-4b7f-beb6-e1670e2ede6a',
			thumb: '/static/images/h%26m/blocks/Dress/Bow_Detail_One_Shoulder_Dress_Fullbody/fullbody_1915.webp',
			modelFile: '/static/models/h%26m/blocks/Dress/Bow_Detail_One_Shoulder_Dress_Fullbody/fullbody_1915.glb',
			blockName: 'fullbody 1915',
			avatar: 'female',
			category: 'Dress',
			collection: 'h&m',
			templateId: '5b415153-c832-43c8-b2d1-31188602f768',
			templateName: 'Bow Detail One Shoulder Dress',
			templateCategory: 'Dress',
		},
		{
			_id: 'c5991125-7113-46d6-bce0-33620b205ae8',
			thumb: '/static/images/h%26m/blocks/Dress/Draped_Halterneck_Dress_Fullbody/fullbody_1914.webp',
			modelFile: '/static/models/h%26m/blocks/Dress/Draped_Halterneck_Dress_Fullbody/fullbody_1914.glb',
			blockName: 'fullbody 1914',
			avatar: 'female',
			category: 'Dress',
			collection: 'h&m',
			templateId: 'bd87de0a-0286-4c18-b2bc-0cd75466bc12',
			templateName: 'Draped Halterneck Dress',
			templateCategory: 'Dress',
		},
		{
			_id: '4ef75be5-a999-47aa-af12-90b738306b6a',
			thumb: '/static/images/h%26m/blocks/Dress/Draped_One_Shoulder_Dress_Fullbody/fullbody_1922.webp',
			modelFile: '/static/models/h%26m/blocks/Dress/Draped_One_Shoulder_Dress_Fullbody/fullbody_1922.glb',
			blockName: 'fullbody 1922',
			avatar: 'female',
			category: 'Dress',
			collection: 'h&m',
			templateId: '1d080b9b-854a-458d-9974-d06052331b11',
			templateName: 'Draped One Shoulder Dress',
			templateCategory: 'Dress',
		},
		{
			_id: '32538e89-e7eb-4a2b-a671-dcfc18bbef53',
			thumb: '/static/images/h%26m/blocks/Pants/Jeans_Short_Pants/pants_1912.webp',
			modelFile: '/static/models/h%26m/blocks/Pants/Jeans_Short_Pants/pants_1912.glb',
			blockName: 'pants 1912',
			avatar: 'female',
			category: 'Pants',
			collection: 'h&m',
			templateId: 'b7dce5b7-8f11-48c0-b171-13d0d369ee1b',
			templateName: 'Jeans Short',
			templateCategory: 'Pants',
		},
		{
			_id: 'e627f21b-b733-4e7b-a690-a1ade3d85e0c',
			thumb: '/static/images/h%26m/blocks/Pants/Jersey_Pants_Pants/wp_pants_1909.webp',
			modelFile: '/static/models/h%26m/blocks/Pants/Jersey_Pants_Pants/wp_pants_1909.glb',
			blockName: 'wp pants 1909',
			avatar: 'female',
			category: 'Pants',
			collection: 'h&m',
			templateId: '54583898-f814-4d51-a522-3b81fa5cc769',
			templateName: 'Jersey Pants',
			templateCategory: 'Pants',
		},
		{
			_id: 'd60a0e64-7a9c-4b0f-94c9-d1da77cea3a2',
			thumb: '/static/images/h%26m/blocks/Top/Cap_Sleeved_Top_Bodice/bodice_1908.webp',
			modelFile: '/static/models/h%26m/blocks/Top/Cap_Sleeved_Top_Bodice/bodice_1908.glb',
			blockName: 'bodice 1908',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h&m',
			templateId: '231f4078-2195-4385-a481-28d51904bc2e',
			templateName: 'Cap Sleeved top',
			templateCategory: 'Top',
		},
		{
			_id: 'b8e370bd-26f5-4aae-a8cd-58c42ef2688a',
			thumb: '/static/images/h%26m/blocks/Top/Bandeau_peplum_top_Bodice/bodice_1913.webp',
			modelFile: '/static/models/h%26m/blocks/Top/Bandeau_peplum_top_Bodice/bodice_1913.glb',
			blockName: 'bodice 1913',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h&m',
			templateId: '969b221c-23fb-4177-b53e-53f0752c343f',
			templateName: 'Bandeau peplum top',
			templateCategory: 'Top',
		},
		{
			_id: '06e3ba9f-034e-439a-a1ab-e1b72aa4170d',
			thumb: '/static/images/h%26m/blocks/Top/Crinkled_jersey_top_Bodice/bodice_1923.webp',
			modelFile: '/static/models/h%26m/blocks/Top/Crinkled_jersey_top_Bodice/bodice_1923.glb',
			blockName: 'bodice 1923',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h&m',
			templateId: '7439e9cd-eb53-4a2c-b01a-95db66f5435a',
			templateName: 'Crinkled jersey top',
			templateCategory: 'Top',
		},
		{
			_id: 'd66850be-fcad-4a9d-9ce5-58b46a8f63b0',
			thumb: '/static/images/h%26m/blocks/Top/Cotton_seersucker_top_Bodice/bodice_1911.webp',
			modelFile: '/static/models/h%26m/blocks/Top/Cotton_seersucker_top_Bodice/bodice_1911.glb',
			blockName: 'bodice 1911',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h&m',
			templateId: '6c500f31-912e-483a-a99e-0da49c5dc1d5',
			templateName: 'Cotton seersucker top',
			templateCategory: 'Top',
		},
		{
			_id: 'ce44f9d2-917f-44d5-be53-bb6676ac5361',
			thumb: '/static/images/h%26m/blocks/Top/Frilled_mini_skort_Bodice/bodice_1916.webp',
			modelFile: '/static/models/h%26m/blocks/Top/Frilled_mini_skort_Bodice/bodice_1916.glb',
			blockName: 'bodice 1916',
			avatar: 'female',
			category: 'Bodice',
			collection: 'h&m',
			templateId: 'ba8b27dc-562d-45d3-b408-30a83b585fb9',
			templateName: 'Frilled mini skort',
			templateCategory: 'Top',
		},
	],

	abercrombie: [
		{
			_id: '53e36346-3497-4128-a11d-60fe18281c3c',
			thumb: '/static/images/abercrombie/blocks/Dress/Item_1_Fullbody/fullbody_1905.webp',
			modelFile: '/static/models/abercrombie/blocks/Dress/Item_1_Fullbody/fullbody_1905.glb',
			blockName: 'fullbody 1905',
			avatar: 'female',
			category: 'Full Body',
			collection: 'abercrombie',
			templateId: '75aafa30-fa99-47ad-8fe5-f84a92d28674',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	'oceania-london': [
		{
			_id: '6a26c924-5d03-4e4b-9c53-806ad657bbce',
			thumb: '/static/images/oceania-london/blocks/Dress/Item_1_Fullbody/fullbody_1888.webp',
			modelFile: '/static/models/oceania-london/blocks/Dress/Item_1_Fullbody/fullbody_1888.glb',
			blockName: 'fullbody 1888',
			avatar: 'female',
			category: 'Full Body',
			collection: 'oceania-london',
			templateId: 'e8ab0090-5b6f-455a-beda-de7f760b1373',
			templateName: 'Item 1',
			templateCategory: 'Dress',
		},
	],

	cortana: [
		{
			_id: 'ef59727b-ac8a-4e35-a834-34a47366bbbf',
			thumb: '/static/images/cortana/blocks/Dress/orange_silk_crepe_halter_dress_Fullbody/fullbody_1941.webp',
			modelFile: '/static/models/cortana/blocks/Dress/orange_silk_crepe_halter_dress_Fullbody/fullbody_1941.glb',
			blockName: 'fullbody 1941',
			avatar: 'female',
			category: 'Dress',
			collection: 'cortana',
			templateId: 'cb2713d5-aed1-45af-a5c7-0bdc0b9eb798',
			templateName: 'orange silk crepe halter dress',
			templateCategory: 'Dress',
		},
	],
}

// TODO: Update this to use the blocks from the database
export const blocks = toSolidSignal<Block[]>(() => {
	const result: Block[] = []
	for (const blockList of Object.values(legacyBlocks)) result.push(...blockList)
	return result
})

export const getBlocksByCollection = (collectionOrSlug: string | string[] | Collection) => {
	if (Array.isArray(collectionOrSlug)) return blocks().filter(block => collectionOrSlug.includes(block.collection))
	return typeof collectionOrSlug === 'string'
		? blocks().filter(block => block.collection === collectionOrSlug)
		: blocks().filter(block => block.collection === collectionOrSlug.slug)
}
