import type {Block} from '../types/block'

export const blocks: Record<string, Block[]> = {
	
		moidien: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Accessories/Item%202%20_%20bag/bag_122.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Accessories/Item%202%20_%20bag/bag_122.gltf',
		blockName: 'bag 122',
		avatar: 'Male',
		category: 'Bag',
		templateId: 'Item 2',
		templateName: 'Item 2',
		templateCategory: 'Accessories',
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Accessories/Item%201%20_%20hat/hat_125.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Accessories/Item%201%20_%20hat/hat_125.gltf',
		blockName: 'hat 125',
		avatar: 'Male',
		category: 'Hat',
		templateId: 'Item 1',
		templateName: 'Item 1',
		templateCategory: 'Accessories',
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Dress/Item%2012%20_%20bodice/bodice%20_1426.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Dress/Item%2012%20_%20bodice/bodice%20_1426.gltf',
		blockName: 'bodice  1426',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 12',
		templateName: 'Item 12',
		templateCategory: 'Dress',
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Dress/Item%203%20_%20fullbody/fullbody_125.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Dress/Item%203%20_%20fullbody/fullbody_125.gltf',
		blockName: 'fullbody 125',
		avatar: 'Male',
		category: 'Full Body',
		templateId: 'Item 3',
		templateName: 'Item 3',
		templateCategory: 'Dress',
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Shirt/Item%209%20_%20bodice/shirt%20_126.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Shirt/Item%209%20_%20bodice/shirt%20_126.gltf',
		blockName: 'shirt  126',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 9',
		templateName: 'Item 9',
		templateCategory: 'Shirt',
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Shirt/Item+11+_+bodice/bodice_123.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Shirt/Item%2011%20_%20bodice/bodice_123.gltf',
		blockName: 'bodice 123',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 11',
		templateName: 'Item 11',
		templateCategory: 'Shirt',
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Shirt/Item%208%20_%20Bodice/bodice_1455.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Shirt/Item%208%20_%20Bodice/bodice_1455.gltf',
		blockName: 'bodice 1455',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 8',
		templateName: 'Item 8',
		templateCategory: 'Shirt',
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Pants/Item%207_Pants/pants_130.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Pants/Item+7_Pants/pants_130.gltf',
		blockName: 'pants 130',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 7',
		templateName: 'Item 7',
		templateCategory: 'Pants',
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/blocks/Pants/Item%204_pants/pants%20_124.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/moidien/blocks/Pants/Item%204_pants/pants%20_124.gltf',
		blockName: 'pants  124',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 4',
		templateName: 'Item 4',
		templateCategory: 'Pants',
	}
],
	
}
