import type {Block} from '../types/block'

export const blocks: Record<string, Block[]> = {
	
		speed: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%2021%20_%20Pants/Pants%201395.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%2021%20_%20Pants/Pants%201395.gltf',
		blockName: 'Pants 1395',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 21',
		templateName: 'Item 21',
		templateCategory: 'Pants',
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%2017%20_%20Pants/Pants%201389.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%2017%20_%20Pants/Pants%201389.gltf',
		blockName: 'Pants 1389',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 17',
		templateName: 'Item 17',
		templateCategory: 'Pants',
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%2015%20_%20Pants/Pants%201387.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%2015%20_%20Pants/Pants%201387.gltf',
		blockName: 'Pants 1387',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 15',
		templateName: 'Item 15',
		templateCategory: 'Pants',
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%2012%20_%20Pants/Pants%201379.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%2012%20_%20Pants/Pants%201379.gltf',
		blockName: 'Pants 1379',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 12',
		templateName: 'Item 12',
		templateCategory: 'Pants',
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%209%20_%20Pants/Pants%201375.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%209%20_%20Pants/Pants%201375.gltf',
		blockName: 'Pants 1375',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 9',
		templateName: 'Item 9',
		templateCategory: 'Pants',
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Pants/Item%203%20_%20Pants/Pants%201362.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Pants/Item%203%20_%20Pants/Pants%201362.gltf',
		blockName: 'Pants 1362',
		avatar: 'Male',
		category: 'Pants',
		templateId: 'Item 3',
		templateName: 'Item 3',
		templateCategory: 'Pants',
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2022%20_%20Sleeves/Sleeves%201401.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2022%20_%20Sleeves/Sleeves%201401.gltf',
		blockName: 'Sleeves 1401',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 22',
		templateName: 'Item 22',
		templateCategory: 'Jacket',
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2022%20_%20Bodice/Bodice%201400.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2022%20_%20Bodice/Bodice%201400.gltf',
		blockName: 'Bodice 1400',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 22',
		templateName: 'Item 22',
		templateCategory: 'Jacket',
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2019%20_%20Sleeves/Sleeves%201399.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2019%20_%20Sleeves/Sleeves%201399.gltf',
		blockName: 'Sleeves 1399',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 19',
		templateName: 'Item 19',
		templateCategory: 'Jacket',
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2019%20_%20Bodice/Bodice%201397.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2019%20_%20Bodice/Bodice%201397.gltf',
		blockName: 'Bodice 1397',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 19',
		templateName: 'Item 19',
		templateCategory: 'Jacket',
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2014%20_%20Bodice/Bodice%201385.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2014%20_%20Bodice/Bodice%201385.gltf',
		blockName: 'Bodice 1385',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 14',
		templateName: 'Item 14',
		templateCategory: 'Jacket',
	},
	{
		_id: '12',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2011%20_%20Sleeves/Sleeves%201392.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2011%20_%20Sleeves/Sleeves%201392.gltf',
		blockName: 'Sleeves 1392',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 11',
		templateName: 'Item 11',
		templateCategory: 'Jacket',
	},
	{
		_id: '13',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%2011%20_%20Bodice/Bodice%201391.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%2011%20_%20Bodice/Bodice%201391.gltf',
		blockName: 'Bodice 1391',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 11',
		templateName: 'Item 11',
		templateCategory: 'Jacket',
	},
	{
		_id: '14',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%208%20_%20Bodice/Bodice%201378.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%208%20_%20Bodice/Bodice%201378.gltf',
		blockName: 'Bodice 1378',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 8',
		templateName: 'Item 8',
		templateCategory: 'Jacket',
	},
	{
		_id: '15',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%205%20_%20Sleeves/Sleeves%201370.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%205%20_%20Sleeves/Sleeves%201370.gltf',
		blockName: 'Sleeves 1370',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 5',
		templateName: 'Item 5',
		templateCategory: 'Jacket',
	},
	{
		_id: '16',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%205%20_%20Bodice/Bodice%201369.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%205%20_%20Bodice/Bodice%201369.gltf',
		blockName: 'Bodice 1369',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 5',
		templateName: 'Item 5',
		templateCategory: 'Jacket',
	},
	{
		_id: '17',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Jacket/Item%202%20_%20Bodice/Bodice%201364.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Jacket/Item%202%20_%20Bodice/Bodice%201364.gltf',
		blockName: 'Bodice 1364',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 2',
		templateName: 'Item 2',
		templateCategory: 'Jacket',
	},
	{
		_id: '18',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2020%20_%20Sleeves%20Raglan/Sleeves%201394.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2020%20_%20Sleeves%20Raglan/Sleeves%201394.gltf',
		blockName: 'Sleeves 1394',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 20',
		templateName: 'Item 20',
		templateCategory: 'Shirt',
	},
	{
		_id: '19',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2020%20_%20Bodice%20Raglan/Bodice%201393.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2020%20_%20Bodice%20Raglan/Bodice%201393.gltf',
		blockName: 'Bodice 1393',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 20',
		templateName: 'Item 20',
		templateCategory: 'Shirt',
	},
	{
		_id: '20',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2018%20_%20Sleeves/Sleeves%201398.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2018%20_%20Sleeves/Sleeves%201398.gltf',
		blockName: 'Sleeves 1398',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 18',
		templateName: 'Item 18',
		templateCategory: 'Shirt',
	},
	{
		_id: '21',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2018%20_%20Bodice/Bodice%201396.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2018%20_%20Bodice/Bodice%201396.gltf',
		blockName: 'Bodice 1396',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 18',
		templateName: 'Item 18',
		templateCategory: 'Shirt',
	},
	{
		_id: '22',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2016%20_%20Sleeves/Sleeves%201390.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2016%20_%20Sleeves/Sleeves%201390.gltf',
		blockName: 'Sleeves 1390',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 16',
		templateName: 'Item 16',
		templateCategory: 'Shirt',
	},
	{
		_id: '23',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2016%20_%20Bodice/Bodice%201388.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2016%20_%20Bodice/Bodice%201388.gltf',
		blockName: 'Bodice 1388',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 16',
		templateName: 'Item 16',
		templateCategory: 'Shirt',
	},
	{
		_id: '24',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2013%20_%20Sleeves/Sleeves%201386.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2013%20_%20Sleeves/Sleeves%201386.gltf',
		blockName: 'Sleeves 1386',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 13',
		templateName: 'Item 13',
		templateCategory: 'Shirt',
	},
	{
		_id: '25',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2013%20_%20Bodice/Bodice%201384.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2013%20_%20Bodice/Bodice%201384.gltf',
		blockName: 'Bodice 1384',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 13',
		templateName: 'Item 13',
		templateCategory: 'Shirt',
	},
	{
		_id: '26',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2010%20_%20Sleeves/Sleeves%201382.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2010%20_%20Sleeves/Sleeves%201382.gltf',
		blockName: 'Sleeves 1382',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 10',
		templateName: 'Item 10',
		templateCategory: 'Shirt',
	},
	{
		_id: '27',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%2010%20_%20Bodice/Bodice%201381.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%2010%20_%20Bodice/Bodice%201381.gltf',
		blockName: 'Bodice 1381',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 10',
		templateName: 'Item 10',
		templateCategory: 'Shirt',
	},
	{
		_id: '28',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%207%20_%20Sleeves/Sleeves%201374.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%207%20_%20Sleeves/Sleeves%201374.gltf',
		blockName: 'Sleeves 1374',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 7',
		templateName: 'Item 7',
		templateCategory: 'Shirt',
	},
	{
		_id: '29',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%207%20_%20Bodice/Bodice%201373.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%207%20_%20Bodice/Bodice%201373.gltf',
		blockName: 'Bodice 1373',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 7',
		templateName: 'Item 7',
		templateCategory: 'Shirt',
	},
	{
		_id: '30',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%206%20_%20Sleeves/Sleeves%201372.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%206%20_%20Sleeves/Sleeves%201372.gltf',
		blockName: 'Sleeves 1372',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 6',
		templateName: 'Item 6',
		templateCategory: 'Shirt',
	},
	{
		_id: '31',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%206%20_%20Bodice/Bodice%201371.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%206%20_%20Bodice/Bodice%201371.gltf',
		blockName: 'Bodice 1371',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 6',
		templateName: 'Item 6',
		templateCategory: 'Shirt',
	},
	{
		_id: '32',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%204%20_%20Sleeves/Sleeves%201368.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%204%20_%20Sleeves/Sleeves%201368.gltf',
		blockName: 'Sleeves 1368',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 4',
		templateName: 'Item 4',
		templateCategory: 'Shirt',
	},
	{
		_id: '33',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%204%20_%20Bodice/Bodice%201367.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%204%20_%20Bodice/Bodice%201367.gltf',
		blockName: 'Bodice 1367',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 4',
		templateName: 'Item 4',
		templateCategory: 'Shirt',
	},
	{
		_id: '34',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%201%20_%20Sleeves/Sleeves%201291.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%201%20_%20Sleeves/Sleeves%201291.gltf',
		blockName: 'Sleeves 1291',
		avatar: 'Male',
		category: 'Sleeves',
		templateId: 'Item 1',
		templateName: 'Item 1',
		templateCategory: 'Shirt',
	},
	{
		_id: '35',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/blocks/Shirt/Item%201%20_%20Bodice/Bodice%201289.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/blocks/Shirt/Item%201%20_%20Bodice/Bodice%201289.gltf',
		blockName: 'Bodice 1289',
		avatar: 'Male',
		category: 'Bodice',
		templateId: 'Item 1',
		templateName: 'Item 1',
		templateCategory: 'Shirt',
	}
],
	
}
