import {blocks} from './blocks.js'
import type {Collection} from '../types/types'

export const collections: Collection[] = [
	{
		name: 'GẤP',
		slug: 'gap',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/logo_optimized.webp',
		gender: 'female',
		garmentsCount: blocks.gap?.length ?? 0,
	},
	{
		name: 'The Soul',
		slug: 'the-soul',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/TS-LOGO-_1_.webp',
		gender: 'female',
		garmentsCount: blocks['the-soul']?.length ?? 0,
	},
	{
		name: 'Emwear',
		slug: 'emwear',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Emwear.png',
		gender: 'female',
		garmentsCount: blocks.emwear?.length ?? 0,
	},
	{
		name: 'Duality in Radiance',
		slug: 'duality-in-radiance',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Shri.png',
		gender: 'female',
		garmentsCount: blocks['duality-in-radiance']?.length ?? 0,
	},
	{
		name: 'Metamorphosis',
		slug: 'metamorphosis',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		gender: 'female',
		garmentsCount: blocks['metamorphosis']?.length ?? 0,
	},
	{
		name: 'Zove',
		slug: 'zove',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Zove.png',
		gender: 'female',
		garmentsCount: blocks.zove?.length ?? 0,
	},
	{
		name: 'Movement',
		slug: 'movement',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/HARUKI+ISHIII+(1).webp',
		gender: 'female',
		garmentsCount: blocks['movement']?.length ?? 0,
	},
	{
		name: 'Essence of her',
		slug: 'essence-of-her',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Vaishnavi.webp',
		gender: 'female',
		garmentsCount: blocks['essence-of-her']?.length ?? 0,
	},
	{
		name: 'Shadow Grace',
		slug: 'shadow-grace',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/LOST-CAUSE.webp',
		gender: 'female',
		garmentsCount: blocks['shadow-grace']?.length ?? 0,
	},
	{
		name: '9heure19heure',
		slug: '9heure19heure',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Elise.webp',
		gender: 'male',
		garmentsCount: blocks['9heure19heure']?.length ?? 0,
	},
	{
		name: 'Fige dans le temps',
		slug: 'fige-dans-le-temps',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Atelier+Gourney+(1).webp',
		gender: 'female',
		garmentsCount: blocks['fige-dans-le-temps']?.length ?? 0,
	},
	{
		name: 'Imzad-Man',
		slug: 'imzad-man',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/IMZAD.webp',
		gender: 'male',
		garmentsCount: blocks['imzad-man']?.length ?? 0,
	},
	{
		name: 'Imzad-Woman',
		slug: 'imzad-woman',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/IMZAD.webp',
		gender: 'female',
		garmentsCount: blocks['imzad-woman']?.length ?? 0,
	},
	{
		name: 'One Thousand Poets',
		slug: 'one-thousand-poets',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/One+thousand+poets.webp',
		gender: 'female',
		garmentsCount: blocks['one-thousand-poets']?.length ?? 0,
	},
	{
		name: 'Ja Seng Bu',
		slug: 'ja-seng-bu',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Seng.webp',
		gender: 'female',
		garmentsCount: blocks['ja-seng-bu']?.length ?? 0,
	},
	{
		name: 'Mss Park',
		slug: 'mss-park',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/MISS-PARK-logo_full_-_1_.webp',
		gender: 'female',
		garmentsCount: blocks['mss-park']?.length ?? 0,
	},
	{
		name: 'CHANGES',
		slug: 'changes',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['changes']?.length ?? 0,
	},
	{
		name: 'Animation Test',
		slug: 'animation-test',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['animation-test']?.length ?? 0,
	},

	{
		name: 'anyshape',
		slug: 'anyshape',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['anyshape']?.length ?? 0,
	},
	{
		name: 'baum-und-pferdgarten',
		slug: 'baum-und-pferdgarten',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['baum-und-pferdgarten']?.length ?? 0,
	},
	{
		name: 'bloom.womenswear',
		slug: 'bloom.womenswear',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['bloom.womenswear']?.length ?? 0,
	},
	{
		name: 'cecilie-bahnsen',
		slug: 'cecilie-bahnsen',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cecilie-bahnsen']?.length ?? 0,
	},
	{
		name: 'crescent',
		slug: 'crescent',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['crescent']?.length ?? 0,
	},
	{
		name: 'dario-mittmann',
		slug: 'dario-mittmann',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dario-mittmann']?.length ?? 0,
	},

	{
		name: 'david-black',
		slug: 'david-black',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['david-black']?.length ?? 0,
	},
	{
		name: 'diane',
		slug: 'diane',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['diane']?.length ?? 0,
	},
	{
		name: 'dico',
		slug: 'dico',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dico']?.length ?? 0,
	},
	{
		name: 'dottie',
		slug: 'dottie',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dottie']?.length ?? 0,
	},
	{
		name: 'erroris.ltd',
		slug: 'erroris.ltd',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['erroris.ltd']?.length ?? 0,
	},
	{
		name: 'gola',
		slug: 'gola',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['gola']?.length ?? 0,
	},
	{
		name: 'h2b',
		slug: 'h2b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['h2b']?.length ?? 0,
	},
	{
		name: 'joie-des-roses',
		slug: 'joie-des-roses',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['joie-des-roses']?.length ?? 0,
	},
	{
		name: 'jubin-studio',
		slug: 'jubin-studio',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['jubin-studio']?.length ?? 0,
	},
	{
		name: 'julian-prohaska',
		slug: 'julian-prohaska',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['julian-prohaska']?.length ?? 0,
	},
	{
		name: 'kido',
		slug: 'kido',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['kido']?.length ?? 0,
	},
	{
		name: 'levents',
		slug: 'levents',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['levents']?.length ?? 0,
	},
	{
		name: 'lider',
		slug: 'lider',
		logo: '',
		gender: 'male',
		garmentsCount: blocks['lider']?.length ?? 0,
	},
	{
		name: 'ononmm',
		slug: 'ononmm',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['ononmm']?.length ?? 0,
	},
	{
		name: 'paradise-saigon',
		slug: 'paradise-saigon',
		logo: '',
		gender: 'male',
		garmentsCount: blocks['paradise-saigon']?.length ?? 0,
	},
	{
		name: 'pindiga-ranjith-kumar',
		slug: 'pindiga-ranjith-kumar',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['pindiga-ranjith-kumar']?.length ?? 0,
	},
	{
		name: 'pradies',
		slug: 'pradies',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['pradies']?.length ?? 0,
	},
	{
		name: 'vinaygaia',
		slug: 'vinaygaia',
		logo: '',
		gender: 'male',
		garmentsCount: blocks['vinaygaia']?.length ?? 0,
	},
	{
		name: 'bad-habits',
		slug: 'bad-habits',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['bad-habits']?.length ?? 0,
	},
	{
		name: 'beachclub.official',
		slug: 'beachclub.official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['beachclub.official']?.length ?? 0,
	},
	{
		name: 'cara-club',
		slug: 'cara-club',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cara-club']?.length ?? 0,
	},
	{
		name: 'demobaza',
		slug: 'demobaza',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['demobaza']?.length ?? 0,
	},
	{
		name: 'hani',
		slug: 'hani',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['hani']?.length ?? 0,
	},
	{
		name: 'huelley-rose',
		slug: 'huelley-rose',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['huelley-rose']?.length ?? 0,
	},
	{
		name: 'hurricane-b',
		slug: 'hurricane-b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['hurricane-b']?.length ?? 0,
	},
	{
		name: 'fig.cool-leather',
		slug: 'fig.cool-leather',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['fig.cool-leather']?.length ?? 0,
	},
	{
		name: 'libeworkshop',
		slug: 'libeworkshop',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['libeworkshop']?.length ?? 0,
	},
	{
		name: 'mono-talk',
		slug: 'mono-talk',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['mono-talk']?.length ?? 0,
	},
	{
		name: 'naked',
		slug: 'naked',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['naked']?.length ?? 0,
	},
	{
		name: 'push-push',
		slug: 'push-push',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['push-push']?.length ?? 0,
	},
	{
		name: 'raxada',
		slug: 'raxada',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['raxada']?.length ?? 0,
	},
	{
		name: 'rechick',
		slug: 'rechick',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['rechick']?.length ?? 0,
	},
	{
		name: 'ridkid',
		slug: 'ridkid',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['ridkid']?.length ?? 0,
	},
	{
		name: 'rotate',
		slug: 'rotate',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['rotate']?.length ?? 0,
	},
	{
		name: 'salteye',
		slug: 'salteye',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['salteye']?.length ?? 0,
	},
	{
		name: 'skall',
		slug: 'skall',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['skall']?.length ?? 0,
	},
	{
		name: 'so-vintage-official',
		slug: 'so-vintage-official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['so-vintage-official']?.length ?? 0,
	},
	{
		name: 'sora.m_design',
		slug: 'sora.m_design',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['sora.m_design']?.length ?? 0,
	},
	{
		name: 'ssdslsns',
		slug: 'ssdslsns',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['ssdslsns']?.length ?? 0,
	},
	{
		name: 'stevie-crowne',
		slug: 'stevie-crowne',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['stevie-crowne']?.length ?? 0,
	},
	{
		name: 'tsun',
		slug: 'tsun',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['tsun']?.length ?? 0,
	},
	{
		name: 'tubycatu',
		slug: 'tubycatu',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['tubycatu']?.length ?? 0,
	},
	{
		name: 'whiteplan',
		slug: 'whiteplan',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['whiteplan']?.length ?? 0,
	},
	{
		name: 'zd-eye-of-the-storm',
		slug: 'zd-eye-of-the-storm',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['zd-eye-of-the-storm']?.length ?? 0,
	},
	{
		name: 'katalog-1811',
		slug: 'katalog-1811',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['katalog-1811']?.length ?? 0,
	},
	{
		name: 'H&M',
		slug: 'h&m',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/lgo-h%26m.webp',
		gender: 'female',
		garmentsCount: blocks['h&m']?.length ?? 0,
	},
]
