import {blocks} from './blocks.js'
import type {Collection} from '../types/types'

export const collections: Collection[] = [
	{
		name: 'metamorphosis',
		slug: 'metamorphosis',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['metamorphosis']?.length ?? 0,
	},
	{
		name: 'H&M',
		slug: 'h&m',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/lgo-h%26m.webp',
		gender: 'female',
		garmentsCount: blocks['h&m']?.length ?? 0,
	},
	{
		name: 'anyshape',
		slug: 'anyshape',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['anyshape']?.length ?? 0,
	},
	{
		name: 'ayarabbim',
		slug: 'ayarabbim',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['ayarabbim']?.length ?? 0,
	},
	{
		name: 'baum-und-pferdgarten',
		slug: 'baum-und-pferdgarten',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['baum-und-pferdgarten']?.length ?? 0,
	},
	{
		name: 'bloom.womenswear',
		slug: 'bloom.womenswear',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['bloom.womenswear']?.length ?? 0,
	},
	{
		name: 'bupbes',
		slug: 'bupbes',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['bupbes']?.length ?? 0,
	},
	{
		name: 'call-me-ari',
		slug: 'call-me-ari',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['call-me-ari']?.length ?? 0,
	},
	{
		name: 'cecilie-bahnsen',
		slug: 'cecilie-bahnsen',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cecilie-bahnsen']?.length ?? 0,
	},
	{
		name: 'crescent',
		slug: 'crescent',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['crescent']?.length ?? 0,
	},
	{
		name: 'cuba-vera',
		slug: 'cuba-vera',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cuba-vera']?.length ?? 0,
	},
	{
		name: 'dario-mittmann',
		slug: 'dario-mittmann',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dario-mittmann']?.length ?? 0,
	},
	{
		name: 'givenchy',
		slug: 'givenchy',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['givenchy']?.length ?? 0,
	},
	{
		name: 'dico',
		slug: 'dico',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dico']?.length ?? 0,
	},
	{
		name: 'dottie',
		slug: 'dottie',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['dottie']?.length ?? 0,
	},
	{
		name: 'edini',
		slug: 'edini',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['edini']?.length ?? 0,
	},
	{
		name: 'erroris.ltd',
		slug: 'erroris.ltd',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['erroris.ltd']?.length ?? 0,
	},
	{
		name: 'gola',
		slug: 'gola',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['gola']?.length ?? 0,
	},
	{
		name: 'h2b',
		slug: 'h2b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['h2b']?.length ?? 0,
	},
	{
		name: 'joie-des-roses',
		slug: 'joie-des-roses',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['joie-des-roses']?.length ?? 0,
	},
	{
		name: 'jubin-studio',
		slug: 'jubin-studio',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['jubin-studio']?.length ?? 0,
	},
	{
		name: 'celeste-studio',
		slug: 'celeste-studio',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['celeste-studio']?.length ?? 0,
	},
	{
		name: 'just-etro-gang',
		slug: 'just-etro-gang',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['just-etro-gang']?.length ?? 0,
	},
	{
		name: 'kido',
		slug: 'kido',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['kido']?.length ?? 0,
	},
	{
		name: 'levents',
		slug: 'levents',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['levents']?.length ?? 0,
	},
	{
		name: 'bad-habits',
		slug: 'bad-habits',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['bad-habits']?.length ?? 0,
	},
	{
		name: 'beachclub.official',
		slug: 'beachclub.official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['beachclub.official']?.length ?? 0,
	},
	{
		name: 'berta',
		slug: 'berta',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['berta']?.length ?? 0,
	},
	{
		name: 'cara-club',
		slug: 'cara-club',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cara-club']?.length ?? 0,
	},
	{
		name: 'ceci-cela',
		slug: 'ceci-cela',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['ceci-cela']?.length ?? 0,
	},
	{
		name: 'celine',
		slug: 'celine',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['celine']?.length ?? 0,
	},
	{
		name: 'colin',
		slug: 'colin',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['colin']?.length ?? 0,
	},
	{
		name: 'demobaza',
		slug: 'demobaza',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['demobaza']?.length ?? 0,
	},
	{
		name: 'diane',
		slug: 'diane',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['diane']?.length ?? 0,
	},
	{
		name: 'hani',
		slug: 'hani',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['hani']?.length ?? 0,
	},
	{
		name: 'huelley-rose',
		slug: 'huelley-rose',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['huelley-rose']?.length ?? 0,
	},
	{
		name: 'hurricane-b',
		slug: 'hurricane-b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['hurricane-b']?.length ?? 0,
	},
	{
		name: 'fig.cool-leather',
		slug: 'fig.cool-leather',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['fig.cool-leather']?.length ?? 0,
	},
	{
		name: 'libeworkshop',
		slug: 'libeworkshop',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['libeworkshop']?.length ?? 0,
	},
	{
		name: 'liniss-official',
		slug: 'liniss-official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['liniss-official']?.length ?? 0,
	},
	{
		name: 'meanbldv',
		slug: 'meanbldv',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['meanbldv']?.length ?? 0,
	},
	{
		name: 'milk-white',
		slug: 'milk-white',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['milk-white']?.length ?? 0,
	},
	{
		name: 'mono-talk',
		slug: 'mono-talk',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['mono-talk']?.length ?? 0,
	},
	{
		name: 'monroe-the-label',
		slug: 'monroe-the-label',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['monroe-the-label']?.length ?? 0,
	},
	{
		name: 'naked',
		slug: 'naked',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['naked']?.length ?? 0,
	},
	{
		name: 'nakedandfamousdenim',
		slug: 'nakedandfamousdenim',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['nakedandfamousdenim']?.length ?? 0,
	},
	{
		name: 'zd-eye-of-the-storm',
		slug: 'zd-eye-of-the-storm',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['zd-eye-of-the-storm']?.length ?? 0,
	},
	{
		name: 'abercrombie',
		slug: 'abercrombie',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['abercrombie']?.length ?? 0,
	},
	{
		name: 'oceania-london',
		slug: 'oceania-london',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['oceania-london']?.length ?? 0,
	},
	{
		name: 'cortana',
		slug: 'cortana',
		logo: '',
		gender: 'female',
		garmentsCount: blocks['cortana']?.length ?? 0,
	},
]
