import type {Collection} from '../types/types.js'
import {toSolidSignal} from '../utils.js'
import {blocks} from './blocks.js'

// @deprecated
// Will get replaced with the collections from the database
export const legacyCollections: Collection[] = [
	{
		name: 'metamorphosis',
		slug: 'metamorphosis',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'metamorphosis').length,
	},
	{
		name: 'H&M',
		slug: 'h&m',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/lgo-h%26m.webp',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'h&m').length,
	},
	{
		name: 'anyshape',
		slug: 'anyshape',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'anyshape').length,
	},
	{
		name: 'ayarabbim',
		slug: 'ayarabbim',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'ayarabbim').length,
	},
	{
		name: 'baum-und-pferdgarten',
		slug: 'baum-und-pferdgarten',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'baum-und-pferdgarten').length,
	},
	{
		name: 'bloom.womenswear',
		slug: 'bloom.womenswear',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'bloom.womenswear').length,
	},
	{
		name: 'bupbes',
		slug: 'bupbes',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'bupbes').length,
	},
	{
		name: 'call-me-ari',
		slug: 'call-me-ari',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'call-me-ari').length,
	},
	{
		name: 'cecilie-bahnsen',
		slug: 'cecilie-bahnsen',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'cecilie-bahnsen').length,
	},
	{
		name: 'crescent',
		slug: 'crescent',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'crescent').length,
	},
	{
		name: 'cuba-vera',
		slug: 'cuba-vera',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'cuba-vera').length,
	},
	{
		name: 'dario-mittmann',
		slug: 'dario-mittmann',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'dario-mittmann').length,
	},
	{
		name: 'givenchy',
		slug: 'givenchy',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'givenchy').length,
	},
	{
		name: 'dico',
		slug: 'dico',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'dico').length,
	},
	{
		name: 'dottie',
		slug: 'dottie',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'dottie').length,
	},
	{
		name: 'edini',
		slug: 'edini',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'edini').length,
	},
	{
		name: 'erroris.ltd',
		slug: 'erroris.ltd',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'erroris.ltd').length,
	},
	{
		name: 'gola',
		slug: 'gola',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'gola').length,
	},
	{
		name: 'h2b',
		slug: 'h2b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'h2b').length,
	},
	{
		name: 'joie-des-roses',
		slug: 'joie-des-roses',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'joie-des-roses').length,
	},
	{
		name: 'jubin-studio',
		slug: 'jubin-studio',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'jubin-studio').length,
	},
	{
		name: 'celeste-studio',
		slug: 'celeste-studio',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'celeste-studio').length,
	},
	{
		name: 'just-etro-gang',
		slug: 'just-etro-gang',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'just-etro-gang').length,
	},
	{
		name: 'kido',
		slug: 'kido',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'kido').length,
	},
	{
		name: 'levents',
		slug: 'levents',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'levents').length,
	},
	{
		name: 'bad-habits',
		slug: 'bad-habits',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'bad-habits').length,
	},
	{
		name: 'beachclub.official',
		slug: 'beachclub.official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'beachclub.official').length,
	},
	{
		name: 'berta',
		slug: 'berta',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'berta').length,
	},
	{
		name: 'cara-club',
		slug: 'cara-club',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'cara-club').length,
	},
	{
		name: 'ceci-cela',
		slug: 'ceci-cela',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'ceci-cela').length,
	},
	{
		name: 'celine',
		slug: 'celine',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'celine').length,
	},
	{
		name: 'colin',
		slug: 'colin',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'colin').length,
	},
	{
		name: 'demobaza',
		slug: 'demobaza',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'demobaza').length,
	},
	{
		name: 'diane',
		slug: 'diane',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'diane').length,
	},
	{
		name: 'hani',
		slug: 'hani',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'hani').length,
	},
	{
		name: 'huelley-rose',
		slug: 'huelley-rose',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'huelley-rose').length,
	},
	{
		name: 'hurricane-b',
		slug: 'hurricane-b',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'hurricane-b').length,
	},
	{
		name: 'fig.cool-leather',
		slug: 'fig.cool-leather',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'fig.cool-leather').length,
	},
	{
		name: 'libeworkshop',
		slug: 'libeworkshop',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'libeworkshop').length,
	},
	{
		name: 'liniss-official',
		slug: 'liniss-official',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'liniss-official').length,
	},
	{
		name: 'meanbldv',
		slug: 'meanbldv',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'meanbldv').length,
	},
	{
		name: 'milk-white',
		slug: 'milk-white',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'milk-white').length,
	},
	{
		name: 'mono-talk',
		slug: 'mono-talk',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'mono-talk').length,
	},
	{
		name: 'monroe-the-label',
		slug: 'monroe-the-label',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'monroe-the-label').length,
	},
	{
		name: 'naked',
		slug: 'naked',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'naked').length,
	},
	{
		name: 'nakedandfamousdenim',
		slug: 'nakedandfamousdenim',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'nakedandfamousdenim').length,
	},
	{
		name: 'zd-eye-of-the-storm',
		slug: 'zd-eye-of-the-storm',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'zd-eye-of-the-storm').length,
	},
	{
		name: 'abercrombie',
		slug: 'abercrombie',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'abercrombie').length,
	},
	{
		name: 'oceania-london',
		slug: 'oceania-london',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'oceania-london').length,
	},
	{
		name: 'cortana',
		slug: 'cortana',
		logo: '',
		gender: 'female',
		garmentsCount: blocks().filter(block => block.collection === 'cortana').length,
	},
]

// TODO: Update this to use the collections from the database
// TODO: rename "collections" to something better, we already have Meteor "collections" and a Collection type.
export const collections = toSolidSignal<Collection[]>(() => {
	return legacyCollections
})
