import type {Fabric} from '../types/fabric'

export const fabrics: Record<string, Fabric[]> = {
	moidien: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_10/PLEATED_FABRIC_-_BLACK_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_10/PLEATED_FABRIC_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_10/PLEATED_FABRIC_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_10/PLEATED_FABRIC_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_10/PLEATED_FABRIC_-_BLACK_-_ROUGH.jpg',
		materialName: 'Black',
		category: 'Pleated Fabric',
		templateCategory: 'Accessories',
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_2/PLEATED_FABRIC_-_WHITE_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_2/PLEATED_FABRIC_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_2/PLEATED_FABRIC_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_2/PLEATED_FABRIC_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Accessories/Material_2/PLEATED_FABRIC_-_WHITE_-_ROUGH.jpg',
		materialName: 'White',
		category: 'Pleated Fabric',
		templateCategory: 'Accessories',
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Dress/Material_3/COTTON_-_TAUPE_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Dress/Material_3/COTTON_-_TAUPE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Dress/Material_3/COTTON_-_TAUPE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Dress/Material_3/COTTON_-_TAUPE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Dress/Material_3/COTTON_-_TAUPE_-_ROUGH.jpg',
		materialName: 'Taupe',
		category: 'Cotton',
		templateCategory: 'Dress',
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_9/PLEATED_FABRIC_-_WHITE_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_9/PLEATED_FABRIC_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_9/PLEATED_FABRIC_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_9/PLEATED_FABRIC_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_9/PLEATED_FABRIC_-_WHITE_-_ROUGH.jpg',
		materialName: 'White',
		category: 'Pleated Fabric',
		templateCategory: 'Shirt',
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_12/SEERSUCKER_FABRIC_-_BLACK_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_12/SEERSUCKER_FABRIC_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_12/SEERSUCKER_FABRIC_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_12/SEERSUCKER_FABRIC_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_12/SEERSUCKER_FABRIC_-_BLACK_-_ROUGH.jpg',
		materialName: 'Black',
		category: 'Seersucker Fabric',
		templateCategory: 'Shirt',
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_11/COTTON_-_WHITE_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_11/COTTON_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_11/COTTON_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_11/COTTON_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Material_11/COTTON_-_WHITE_-_ROUGH.jpg',
		materialName: 'White',
		category: 'Cotton',
		templateCategory: 'Shirt',
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Materials_8/CRINKLE_FABRIC_-_NAVY_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Materials_8/CRINKLE_FABRIC_-_NAVY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Materials_8/CRINKLE_FABRIC_-_NAVY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Materials_8/CRINKLE_FABRIC_-_NAVY_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Shirt/Materials_8/CRINKLE_FABRIC_-_NAVY_-_ROUGH.jpg',
		materialName: 'Navy',
		category: 'Crinkle Fabric',
		templateCategory: 'Shirt',
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_7/COTTON_-_BLACK_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_7/COTTON_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_7/COTTON_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_7/COTTON_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_7/COTTON_-_BLACK_-_ROUGH.jpg',
		materialName: 'Black',
		category: 'Cotton',
		templateCategory: 'Pants',
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_4/COTTON_-_TWILL_-_RENDER.png',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_4/COTTON_-_TWILL_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_4/COTTON_-_TWILL_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_4/COTTON_-_TWILL_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/Pants/Material_4/COTTON_-_TWILL_-_ROUGH.jpg',
		materialName: 'Twill',
		category: 'Cotton',
		templateCategory: 'Pants',
	}
	]
}
