import type {Fabric} from '../types/fabric'

export const fabrics: Record<string, Fabric[]> = {
	vaishnavi: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_DUSTY_MOCHA/SILK_-_DUSTY_MOCHA_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_DUSTY_MOCHA/SILK_-_DUSTY_MOCHA_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_DUSTY_MOCHA/SILK_-_DUSTY_MOCHA_-_BASE_COLOR.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_DUSTY_MOCHA/SILK_-_DUSTY_MOCHA_-_DISPLACEMENT.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_DUSTY_MOCHA/SILK_-_DUSTY_MOCHA_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Dusty Mocha',
		category: 'Silk',
		templateCategories: ['Shirt', 'Skirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BLOOD_RED/SILK_-_BLOOD_RED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BLOOD_RED/SILK_-_BLOOD_RED_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BLOOD_RED/SILK_-_BLOOD_RED_-_BASE_COLOR.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BLOOD_RED/SILK_-_BLOOD_RED_-_DISPLACEMENT.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BLOOD_RED/SILK_-_BLOOD_RED_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Blood Red',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_COCONUT_MILK/SILK_-_COCONUT_MILK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_COCONUT_MILK/SILK_-_COCONUT_MILK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_COCONUT_MILK/SILK_-_COCONUT_MILK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_COCONUT_MILK/SILK_-_COCONUT_MILK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_COCONUT_MILK/SILK_-_COCONUT_MILK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Coconut Milk',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SEQUIN_-_281/SEQUIN_-_281_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SEQUIN_-_281/SEQUIN_-_281_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SEQUIN_-_281/SEQUIN_-_281_-_BASE_COLOR.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SEQUIN_-_281/SEQUIN_-_281_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SEQUIN_-_281/SEQUIN_-_281_-_ROUGH.jpg',
		alpha: '',
		materialName: '281',
		category: 'Sequin',
		templateCategories: ['Shirt', 'Skirt'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BEIGE/SILK_-_BEIGE_-_RENDER_%281%29.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BEIGE/SILK_-_BEIGE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BEIGE/SILK_-_BEIGE_-_BASE_COLOR.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BEIGE/SILK_-_BEIGE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/vaishnavi/root/SILK_-_BEIGE/SILK_-_BEIGE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Beige',
		category: 'Silk',
		templateCategories: ['Shirt', 'Skirt'],
	}
	],
	haruki: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CHIFFON_%282AB4C8%29/SILK_-_CHIFFON_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CHIFFON_%282AB4C8%29/SILK_-_CHIFFON_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CHIFFON_%282AB4C8%29/SILK_-_CHIFFON_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CHIFFON_%282AB4C8%29/SILK_-_CHIFFON_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CHIFFON_%282AB4C8%29/SILK_-_CHIFFON_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Chiffon (2ab4c8)',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28E8BBCA%29/SILK_-_CREPE_%28E8BBCA%29_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28E8BBCA%29/SILK_-_CREPE_%28E8BBCA%29_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28E8BBCA%29/SILK_-_CREPE_%28E8BBCA%29_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28E8BBCA%29/SILK_-_CREPE_%28E8BBCA%29_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28E8BBCA%29/SILK_-_CREPE_%28E8BBCA%29_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Crepe (E8bbca)',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28096372%29/SILK_-_CREPE_%28096372%29_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28096372%29/SILK_-_CREPE_%28096372%29_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28096372%29/SILK_-_CREPE_%28096372%29_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28096372%29/SILK_-_CREPE_%28096372%29_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28096372%29/SILK_-_CREPE_%28096372%29_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Crepe (096372)',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28D6E2EA%29/SILK_-_CREPE_%28D6E2EA%29_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28D6E2EA%29/SILK_-_CREPE_%28D6E2EA%29_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28D6E2EA%29/SILK_-_CREPE_%28D6E2EA%29_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28D6E2EA%29/SILK_-_CREPE_%28D6E2EA%29_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE_%28D6E2EA%29/SILK_-_CREPE_%28D6E2EA%29_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Crepe (D6e2ea)',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE/SILK_-_CREPE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE/SILK_-_CREPE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE/SILK_-_CREPE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE/SILK_-_CREPE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/haruki/root/SILK_-_CREPE/SILK_-_CREPE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Crepe',
		category: 'Silk',
		templateCategories: ['Shirt', 'Dress', 'Skirt'],
	}
	],
	lostCause: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_CHARCOAL_GARY/SILK_-_CHARCOAL_GARY_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_CHARCOAL_GARY/SILK_-_CHARCOAL_GARY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_CHARCOAL_GARY/SILK_-_CHARCOAL_GARY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_CHARCOAL_GARY/SILK_-_CHARCOAL_GARY_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_CHARCOAL_GARY/SILK_-_CHARCOAL_GARY_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Charcoal Gary',
		category: 'Silk',
		templateCategories: ['Skirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK/_SILK_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK/_SILK_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK/_SILK_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK/_SILK_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK/_SILK_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Silk',
		templateCategories: ['Top', 'Skirt'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_BLACK_TWISTED/WOOL_-_BLACK_TWISTED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_BLACK_TWISTED/WOOL_-_BLACK_TWISTED_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_BLACK_TWISTED/WOOL_-_BLACK_TWISTED_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_BLACK_TWISTED/WOOL_-_BLACK_TWISTED_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_BLACK_TWISTED/WOOL_-_BLACK_TWISTED_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black Twisted',
		category: 'Wool',
		templateCategories: ['Top'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_ORGANZA_PRINT/SILK_-_ORGANZA_PRINT_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_ORGANZA_PRINT/SILK_-_ORGANZA_PRINT_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_ORGANZA_PRINT/SILK_-_ORGANZA_PRINT_-_BASE.jpg',
		displacement: '',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_ORGANZA_PRINT/SILK_-_ORGANZA_PRINT_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_ORGANZA_PRINT/SILK_-_ORGANZA_PRINT_-_ALPHA.jpg',
		materialName: 'Organza Print',
		category: 'Silk',
		templateCategories: [],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_TWISTED/WOOL_-_TWISTED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_TWISTED/WOOL_-_TWISTED_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_TWISTED/WOOL_-_TWISTED_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_TWISTED/WOOL_-_TWISTED_-_DISPLACEMENT.jpg',
		roughness: '',
		alpha: '',
		materialName: 'Twisted',
		category: 'Wool',
		templateCategories: ['Top', 'Accessories'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/FUR_-_FAKE/FUR_-_FAKE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/FUR_-_FAKE/FUR_-_FAKE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/FUR_-_FAKE/FUR_-_FAKE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/FUR_-_FAKE/FUR_-_FAKE_-_DISPLACEMENT.jpg',
		roughness: '',
		alpha: '',
		materialName: 'Fake',
		category: 'Fur',
		templateCategories: [],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/LEATHER_-_PRINT/LEATHER_-_PRINT_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/LEATHER_-_PRINT/LEATHER_-_PRINT_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/LEATHER_-_PRINT/LEATHER_-_PRINT_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/LEATHER_-_PRINT/LEATHER_-_PRINT_-_DISPLACEMENT.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/LEATHER_-_PRINT/LEATHER_-_PRINT_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Print',
		category: 'Leather',
		templateCategories: ['Top', 'Pants'],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_BLACK_FACE/ABSTRACT_-_BLACK_FACE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_BLACK_FACE/ABSTRACT_-_BLACK_FACE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_BLACK_FACE/ABSTRACT_FACE_-_BLACK_-_BASE.jpg',
		displacement: '',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_BLACK_FACE/ABSTRACT_-_BLACK_FACE_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_BLACK_FACE/ABSTRACT_-_BLACK_FACE_-_ALPHA.jpg',
		materialName: 'Black Face',
		category: 'Abtract',
		templateCategories: ['Pants'],
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_NAVY_FACE/ABTRACT_-_FACE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_NAVY_FACE/ABSTRACT_-_FACE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_NAVY_FACE/ABSTRACT_-_FACE_-_BASE.jpg',
		displacement: '',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_NAVY_FACE/ABSTRACT_-_FACE_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/ABTRACT_-_NAVY_FACE/ABSTRACT_-_FACE_-_ALPHA.jpg',
		materialName: 'Navy Face',
		category: 'Abtract',
		templateCategories: ['Skirt'],
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/TWISTED_-_YARN/TWISTED_-_YARN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/TWISTED_-_YARN/TWISTED_-_YARN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/TWISTED_-_YARN/TWISTED_-_YARN_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/TWISTED_-_YARN/TWISTED_-_YARN_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/TWISTED_-_YARN/TWISTED_-_YARN_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Yarn',
		category: 'Twisted',
		templateCategories: ['Skirt'],
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK_ORGANZA/SILK_-_BLACK_ORGANZA_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK_ORGANZA/SILK_-_BLACK_ORGANZA_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK_ORGANZA/SILK_-_BLACK_ORGANZA_-_BASE.jpg',
		displacement: '',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK_ORGANZA/SILK_-_BLACK_ORGANZA_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/SILK_-_BLACK_ORGANZA/SILK_-_BLACK_ORGANZA_-_ALPHA.jpg',
		materialName: 'Black Organza',
		category: 'Silk',
		templateCategories: ['Accessories'],
	},
	{
		_id: '12',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_YARN/WOOL_-_YARN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_YARN/WOOL_-_YARN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_YARN/WOOL_YARN_-_BASE.jpg',
		displacement: '',
		roughness: '',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/lostCause/root/WOOL_-_YARN/WOOL_-_YARN_-_ALPHA.jpg',
		materialName: 'Yarn',
		category: 'Wool',
		templateCategories: ['Top', 'Dress', 'Skirt', 'Pants'],
	}
	],
	shri: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/FABRIC_-_GOLDEN/FABRIC_-_GOLDEN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/FABRIC_-_GOLDEN/FABRIC_-_GOLDEN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/FABRIC_-_GOLDEN/FABRIC_-_GOLDEN_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/FABRIC_-_GOLDEN/FABRIC_-_GOLDEN_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/FABRIC_-_GOLDEN/FABRIC_-_GOLDEN_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Golden',
		category: 'Fabric',
		templateCategories: ['Shirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SILK_-_BRONZE/SILK_-_BRONZE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SILK_-_BRONZE/SILK_-_BRONZE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SILK_-_BRONZE/SILK_-_BRONZE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SILK_-_BRONZE/SILK_-_BRONZE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SILK_-_BRONZE/SILK_-_BRONZE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Bronze',
		category: 'Silk',
		templateCategories: ['Pants'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/VELVET_-_BLACK/VELVET_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/VELVET_-_BLACK/VELVET_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/VELVET_-_BLACK/VELVET_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/VELVET_-_BLACK/VELVET_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/VELVET_-_BLACK/VELVET_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Velvet',
		templateCategories: ['Shirt'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SCUBA_-_287/SCUBA_-_287_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SCUBA_-_287/SCUBA_-_287_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SCUBA_-_287/SCUBA_-_287_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SCUBA_-_287/SCUBA_-_287_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/shri/root/SCUBA_-_287/SCUBA_-_287_-_ROUGH.jpg',
		alpha: '',
		materialName: '287',
		category: 'Scuba',
		templateCategories: ['Shirt'],
	}
	],
	eliseF: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/KNIT_-_FLEECE/KNIT_-_FLEECE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/KNIT_-_FLEECE/KNIT_-_FLEECE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/KNIT_-_FLEECE/KNIT_-_FLEECE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/KNIT_-_FLEECE/KNIT_-_FLEECE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/KNIT_-_FLEECE/KNIT_-_FLEECE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Fleece',
		category: 'Knit',
		templateCategories: ['Top'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_DUSTY_BLUE/POLY_-_DUSTY_BLUE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_DUSTY_BLUE/POLY_-_DUSTY_BLUE_-_NORMAL_.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_DUSTY_BLUE/POLY_-_DUSTY_BLUE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_DUSTY_BLUE/POLY_-_DUSTY_BLUE_-_DISPLACE_.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_DUSTY_BLUE/POLY_-_DUSTY_BLUE_-_ROUGH_.jpg',
		alpha: '',
		materialName: 'Dusty Blue',
		category: 'Poly',
		templateCategories: ['Pants'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_BACK/DENIM_-_BACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_BACK/DENIM_-_BACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_BACK/DENIM_-_BACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_BACK/DENIM_-_BACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_BACK/DENIM_-_BACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Back',
		category: 'Denim',
		templateCategories: ['Pants'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_CANVAS/STRIPED_-_CANVAS_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_CANVAS/STRIPED_-_CANVAS_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_CANVAS/STRIPED_-_CANVAS_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_CANVAS/STRIPED_-_CANVAS_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_CANVAS/STRIPED_-_CANVAS_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Canvas',
		category: 'Striped',
		templateCategories: ['Top'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_276/DENIM_-_276_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_276/DENIM_-_276_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_276/DENIM_-_276_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_276/DENIM_-_276_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/DENIM_-_276/DENIM_-_276_-_ROUGH.jpg',
		alpha: '',
		materialName: '276',
		category: 'Denim',
		templateCategories: ['Pants'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLYESTER_-_NAVY/POLYESTER_-_NAVY_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLYESTER_-_NAVY/POLYESTER_-_NAVY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLYESTER_-_NAVY/POLYESTER_-_NAVY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLYESTER_-_NAVY/POLYESTER_-_NAVY_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLYESTER_-_NAVY/POLYESTER_-_NAVY_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Navy',
		category: 'Polyester',
		templateCategories: ['Top', 'Pants'],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_LAVENDER_BLUE/_COTTON_-_LAVENDER_BLUE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_LAVENDER_BLUE/COTTON_-_LAVENDER_BLUE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_LAVENDER_BLUE/COTTON_-_LAVENDER_BLUE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_LAVENDER_BLUE/COTTON__-_LAVENDER_BLUE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_LAVENDER_BLUE/COTTON_-_LAVENDER_BLUE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Lavender Blue',
		category: 'Cotton',
		templateCategories: ['Top'],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_ORANGE/COTTON_-_ORANGE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_ORANGE/COTTON_-_ORANGE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_ORANGE/COTTON_-_ORANGE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_ORANGE/COTTON_-_ORANGE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_ORANGE/COTTON_-_ORANGE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Orange',
		category: 'Cotton',
		templateCategories: ['Top', 'Pants'],
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_TANKTOP/STRIPED_-_TANKTOP_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_TANKTOP/STRIPED_-_TANKTOP_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_TANKTOP/STRIPED_-_TANKTOP_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_TANKTOP/STRIPED_-_TANKTOP_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/STRIPED_-_TANKTOP/STRIPED_-_TANKTOP_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Tanktop',
		category: 'Striped',
		templateCategories: ['Top'],
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_WHITE/COTTON_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_WHITE/COTTON_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_WHITE/COTTON_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_WHITE/COTTON_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/COTTON_-_WHITE/COTTON_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Cotton',
		templateCategories: ['Top'],
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_TWILL/POLY_-_TWILL_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_TWILL/POLY_-_TWILL_-_NORMAL_.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_TWILL/POLY_-_TWILL_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_TWILL/POLY_-_TWILL_-_DISPLACE_.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/eliseF/root/POLY_-_TWILL/POLY_-_TWILL_-_ROUGH_.jpg',
		alpha: '',
		materialName: 'Twill',
		category: 'Poly',
		templateCategories: ['Pants', 'Top'],
	}
	],
	oofya: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_GRAY/COTTON_-_GRAY_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_GRAY/COTTON_-_GRAY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_GRAY/COTTON_-_GRAY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_GRAY/COTTON_-_GRAY_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_GRAY/COTTON_-_GRAY_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Gray',
		category: 'Cotton',
		templateCategories: ['Dress', 'Shirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GRID/CORDUROY_-_GRID_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GRID/CORDUROY_-_GRID_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GRID/CORDUROY_-_GRID_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GRID/CORDUROY_-_GRID_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GRID/CORDUROY_-_GRID_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Grid',
		category: 'Corduroy',
		templateCategories: ['Skirt'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Taffeta',
		templateCategories: ['Accessory', 'Shirt'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/3D_-_SQUARE/3D_-_SQUARE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/3D_-_SQUARE/3D_-_SQUARE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/3D_-_SQUARE/3D_-_SQUARE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/3D_-_SQUARE/3D_-_SQUARE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/3D_-_SQUARE/3D_-_SQUARE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Square',
		category: '3d',
		templateCategories: ['Accessory'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GOLDEN_BROWN_GRID/CORDUROY_-_GOLDEN_BROWN_GRID_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GOLDEN_BROWN_GRID/CORDUROY_-_GOLDEN_BROWN_GRID_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GOLDEN_BROWN_GRID/CORDUROY_-_GOLDEN_BROWN_GRID_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GOLDEN_BROWN_GRID/CORDUROY_-_GOLDEN_BROWN_GRID_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/CORDUROY_-_GOLDEN_BROWN_GRID/CORDUROY_-_GOLDEN_BROWN_GRID_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Golden Brown Grid',
		category: 'Corduroy',
		templateCategories: ['Accessory'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK_SEETHROUGH/COTTON_-_BLACK_SEETHROUGH_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK_SEETHROUGH/COTTON_-_BLACK_SEETHROUGH_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK_SEETHROUGH/COTTON_-_BLACK_SEETHROUGH_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK_SEETHROUGH/COTTON_-_BLACK_SEETHROUGH_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK_SEETHROUGH/COTTON_-_BLACK_SEETHROUGH_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black Seethrough',
		category: 'Cotton',
		templateCategories: [],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_WHITE/COTTON_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_WHITE/COTTON_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_WHITE/COTTON_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_WHITE/COTTON_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_WHITE/COTTON_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Cotton',
		templateCategories: ['Shirt'],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK/COTTON_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK/COTTON_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK/COTTON_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK/COTTON_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/oofya/root/COTTON_-_BLACK/COTTON_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Cotton',
		templateCategories: ['Dress', 'Pants', 'Shirt'],
	}
	],
	theSoul: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/COTTON_-_WHITE/COTTON_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/COTTON_-_WHITE/COTTON_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/COTTON_-_WHITE/COTTON_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/COTTON_-_WHITE/COTTON_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/COTTON_-_WHITE/COTTON_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Cotton',
		templateCategories: ['Top'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TWEED_-_331/TWEED_-_331_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TWEED_-_331/TWEED_-_331_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TWEED_-_331/TWEED_-_331_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TWEED_-_331/TWEED_-_331_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TWEED_-_331/TWEED_-_331_-_ROUGH.jpg',
		alpha: '',
		materialName: '331',
		category: 'Tweed',
		templateCategories: ['Top'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/WOOL_-_OLIVE_GRAY/WOOL_-_OLIVE_GRAY_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/WOOL_-_OLIVE_GRAY/WOOL_-_OLIVE_GRAY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/WOOL_-_OLIVE_GRAY/WOOL_-_OLIVE_GRAY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/WOOL_-_OLIVE_GRAY/WOOL_-_OLIVE_GRAY_-_DISPLACE.jpg',
		roughness: '',
		alpha: '',
		materialName: 'Olive Gray',
		category: 'Wool',
		templateCategories: ['Pants', 'Top'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SUITING_-_HONEY_MUSTARD/SUITING_-_HONEY_MUSTARD_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SUITING_-_HONEY_MUSTARD/SUITING_-_HONEY_MUSTARD_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SUITING_-_HONEY_MUSTARD/SUITING_-_HONEY_MUSTARD_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SUITING_-_HONEY_MUSTARD/SUITING_-_HONEY_MUSTARD_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SUITING_-_HONEY_MUSTARD/SUITING_-_HONEY_MUSTARD_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Honey Mustard',
		category: 'Suiting',
		templateCategories: ['Pants', 'Top'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/PRINT_CHIFFON_-_FLORAL/PRINT_CHIFFON_-_FLORAL_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/PRINT_CHIFFON_-_FLORAL/PRINT_CHIFFON_-_FLORAL_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/PRINT_CHIFFON_-_FLORAL/PRINT_CHIFFON_-_FLORAL_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/PRINT_CHIFFON_-_FLORAL/PRINT_CHIFFON_-_FLORAL_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/PRINT_CHIFFON_-_FLORAL/PRINT_CHIFFON_-_FLORAL_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Floral',
		category: 'Print Chiffon',
		templateCategories: ['Dress'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SATEEN_-_BLACK/SATEEN_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SATEEN_-_BLACK/SATEEN_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SATEEN_-_BLACK/SATEEN_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SATEEN_-_BLACK/SATEEN_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SATEEN_-_BLACK/SATEEN_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Sateen',
		templateCategories: ['Dress'],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/TAFFETA_-_BLACK/TAFFETA_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Taffeta',
		templateCategories: ['Dress'],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/LACE_-_WHITE_FLOWER_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/LACE_-_WHITE_FLOWER_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/LACE_-_WHITE_FLOWER_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/LACE_-_WHITE_FLOWER_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/WHITE_LACE_FLOWER_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_WHITE_FLOWER/LACE_-_WHITE_FLOWER_-_ALPHA.jpg',
		materialName: 'White Flower',
		category: 'Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/LACE_-_FLOWER/LACE_-_FLOWER_-_ALPHA.jpg',
		materialName: 'Flower',
		category: 'Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SILK_-_TAN/SILK_-_TAN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SILK_-_TAN/SILK_-_TAN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SILK_-_TAN/SILK_-_TAN_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SILK_-_TAN/SILK_-_TAN_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/theSoul/root/SILK_-_TAN/SILK_-_TAN_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Tan',
		category: 'Silk',
		templateCategories: ['Dress'],
	}
	],
	moidien: [
	{
		_id: '1',
		thumb: '',
		normal: '',
		baseColor: '',
		displacement: '',
		roughness: '',
		alpha: '',
		materialName: 'Brown',
		category: 'Pleated',
		templateCategories: ['Shirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/WASHED_-_T-SHIRT/WASHED_-_T-SHIRT_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/WASHED_-_T-SHIRT/WASHED_-_T-SHIRT_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/WASHED_-_T-SHIRT/WASHED_-_T-SHIRT_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/WASHED_-_T-SHIRT/WASHED_-_T-SHIRT_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/WASHED_-_T-SHIRT/WASHED_-_T-SHIRT_-_ROUGH.jpg',
		alpha: '',
		materialName: 'T',
		category: 'Washed',
		templateCategories: ['Shirt'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_WHITE/PLEATED_FABRIC_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_WHITE/PLEATED_FABRIC_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_WHITE/PLEATED_FABRIC_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_WHITE/PLEATED_FABRIC_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_WHITE/PLEATED_FABRIC_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Pleated',
		templateCategories: ['Shirt'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/TWILL_-_235/COTTON_-_TWILL_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/TWILL_-_235/COTTON_-_TWILL_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/TWILL_-_235/COTTON_-_TWILL_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/TWILL_-_235/COTTON_-_TWILL_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/TWILL_-_235/COTTON_-_TWILL_-_ROUGH.jpg',
		alpha: '',
		materialName: '235',
		category: 'Twill',
		templateCategories: ['Pants'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_RANDOM/PLEATED_-_RANDOM_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_RANDOM/PLEATED_-_RANDOM_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_RANDOM/PLEATED_-_RANDOM_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_RANDOM/PLEATED_-_RANDOM_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/PLEATED_-_RANDOM/PLEATED_-_RANDOM_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Random',
		category: 'Pleated',
		templateCategories: ['Bag'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/POLY_-_JACQUARD/POLY_-_JACQUARD_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/POLY_-_JACQUARD/POLY_-_JACQUARD_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/POLY_-_JACQUARD/POLY_-_JACQUARD_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/POLY_-_JACQUARD/POLY_-_JACQUARD_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/POLY_-_JACQUARD/POLY_-_JACQUARD_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Jacquard',
		category: 'Poly',
		templateCategories: ['Jacket'],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BROWN/COTTON_-_BROWN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BROWN/COTTON_-_BROWN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BROWN/COTTON_-_BROWN_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BROWN/COTTON_-_BROWN_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BROWN/COTTON_-_BROWN_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Brown',
		category: 'Cotton',
		templateCategories: [],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BLACK/COTTON_-_BLACK_%28RENDER%29.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BLACK/COTTON_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BLACK/COTTON_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BLACK/COTTON_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_BLACK/COTTON_-_BLACK_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Black',
		category: 'Cotton',
		templateCategories: [],
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/CRINKLE_FABRIC_-_NAVY/CRINKLE_FABRIC_-_NAVY_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/CRINKLE_FABRIC_-_NAVY/CRINKLE_FABRIC_-_NAVY_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/CRINKLE_FABRIC_-_NAVY/CRINKLE_FABRIC_-_NAVY_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/CRINKLE_FABRIC_-_NAVY/CRINKLE_FABRIC_-_NAVY_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/CRINKLE_FABRIC_-_NAVY/CRINKLE_FABRIC_-_NAVY_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Navy',
		category: 'Crinkle Fabric',
		templateCategories: ['Jacket'],
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_TAUPE/COTTON_-_TAUPE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_TAUPE/COTTON_-_TAUPE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_TAUPE/COTTON_-_TAUPE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_TAUPE/COTTON_-_TAUPE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_TAUPE/COTTON_-_TAUPE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Taupe',
		category: 'Cotton',
		templateCategories: ['Dress'],
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_BLACK_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_BLACK_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_BLACK_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_BLACK_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_BLACK_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/SEERSUCKER_FABRIC_-_BLACK/SEERSUCKER_FABRIC_-_ALPHA.jpg',
		materialName: 'Black',
		category: 'Seersucker Fabric',
		templateCategories: ['Shirt', 'Pants'],
	},
	{
		_id: '12',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_WHITE/COTTON_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_WHITE/COTTON_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_WHITE/COTTON_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_WHITE/COTTON_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/moidien/root/COTTON_-_WHITE/COTTON_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Cotton',
		templateCategories: ['Shirt'],
	}
	],
	emwear: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_WHITE/LACE_-_WHITE_-_ALPHA.jpg',
		materialName: 'White',
		category: 'Lace',
		templateCategories: ['Skirt'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_WHITE/SILK_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_WHITE/SILK_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_WHITE/SILK_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_WHITE/SILK_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_WHITE/SILK_-_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'White',
		category: 'Silk',
		templateCategories: ['Top'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_-_FFFAED/SILK_-_SEETHROUGH_FFFAED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_-_FFFAED/SILK_-_SEETHROUGH_FFFAED_-_NORMAL.jpg',
		baseColor: '',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_-_FFFAED/SILK_-_SEETHROUGH_FFFAED_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_-_FFFAED/SILK_-_SEETHROUGH_FFFAED_-_FFFAED.jpg',
		alpha: '',
		materialName: 'Seethrough',
		category: 'Silk',
		templateCategories: [],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFFAED/SILK_-_FFFAED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFFAED/SILK_-_FFFAED_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFFAED/SILK_-_FFFAED_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFFAED/SILK_-_FFFAED_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFFAED/SILK_-_FFFAED_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Fffaed',
		category: 'Silk',
		templateCategories: ['Dress', 'Coat'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_FLOWER/MESH_-_FLOWER_-_ALPHA.jpg',
		materialName: 'Flower',
		category: 'Mesh',
		templateCategories: ['Coat'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_CCE9FF/SILK_-_SEETHROUGH_CCE9FF_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_CCE9FF/SILK_-_SEETHROUGH_CCE9FF_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_CCE9FF/SILK_-_SEETHROUGH_CCE9FF_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_CCE9FF/SILK_-_SEETHROUGH_CCE9FF_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_SEETHROUGH_CCE9FF/SILK_-_SEETHROUGH_CCE9FF_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Seethrough Cce9ff',
		category: 'Silk',
		templateCategories: ['Coat', 'Dress'],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_CCE9FF/SILK_-_CCE9FF_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_CCE9FF/SILK_-_CCE9FF_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_CCE9FF/SILK_-_CCE9FF_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_CCE9FF/SILK_-_CCE9FF_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_CCE9FF/SILK_-_CCE9FF_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Cce9ff',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_FFE6F2/LACE_-_FFE6F2_-_ALPHA.jpg',
		materialName: 'Ffe6f2',
		category: 'Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFE6F2/SILK_-_FFE6F2_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFE6F2/SILK_-_FFE6F2_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFE6F2/SILK_-_FFE6F2_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFE6F2/SILK_-_FFE6F2_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFE6F2/SILK_-_FFE6F2_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Ffe6f2',
		category: 'Silk',
		templateCategories: ['Dress', 'Coat'],
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_OFF_WHITE/SILK_-_OFF_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_OFF_WHITE/SILK_-_OFF_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_OFF_WHITE/SILK_-_OFF_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_OFF_WHITE/SILK_-_OFF_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_OFF_WHITE/SILK_-_OFF_WHITE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Off White',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFC85A/SILK_-_FFC85A_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFC85A/SILK_-_FFC85A_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFC85A/SILK_-_FFC85A_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFC85A/SILK_-_FFC85A_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFC85A/SILK_-_FFC85A_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Ffc85a',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '12',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFEBB7/SILK_-_FFEBB7_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFEBB7/SILK_-_FFEBB7_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFEBB7/SILK_-_FFEBB7_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFEBB7/SILK_-_FFEBB7_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_FFEBB7/SILK_-_FFEBB7_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Ffebb7',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '13',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/MESH_-_LAVENDER_BLUSH/MESH_-_LAVENDER_BLUSH_-_ALPHA.jpg',
		materialName: 'Lavender Blush',
		category: 'Mesh',
		templateCategories: ['Coat'],
	},
	{
		_id: '14',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LAVENDER_BLUSH/LACE_-_LAVENDER_BLUSH_-_ALPHA.jpg',
		materialName: 'Lavender Blush',
		category: 'Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '15',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LAVENDER_BLUSH/SILK_-_LAVENDER_BLUSH_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LAVENDER_BLUSH/SILK_-_LAVENDER_BLUSH_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LAVENDER_BLUSH/SILK_-_LAVENDER_BLUSH_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LAVENDER_BLUSH/SILK_-_LAVENDER_BLUSH_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LAVENDER_BLUSH/SILK_-_LAVENDER_BLUSH_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Lavender Blush',
		category: 'Silk',
		templateCategories: ['Dress'],
	},
	{
		_id: '16',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LIGHT_CREAM/LACE_-_LIGHT_CREAM_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LIGHT_CREAM/LACE_-_LIGHT_CREAM_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LIGHT_CREAM/LIGHT_CREAM_LACE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LIGHT_CREAM/LACE_-_LIGHT_CREAM_-_DISPLACE.jpg',
		roughness: '',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/LACE_-_LIGHT_CREAM/LACE_-_LIGHT_CREAM_-_ALPHA.jpg',
		materialName: 'Light Cream',
		category: 'Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '17',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LIGHT_CREAM/SILK_-_LIGHT_CREAM_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LIGHT_CREAM/SILK_-_LIGHT_CREAM_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LIGHT_CREAM/SILK_-_LIGHT_CREAM_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LIGHT_CREAM/SILK_-_LIGHT_CREAM_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/emwear/root/SILK_-_LIGHT_CREAM/SILK_-_LIGHT_CREAM_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Light Cream',
		category: 'Silk',
		templateCategories: ['Dress'],
	}
	],
	atelierGourney: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/METALLIC_-_FRINGE/METALLIC_-_FRINGE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/METALLIC_-_FRINGE/METALLIC_-_FRINGE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/METALLIC_-_FRINGE/METALLIC_-_FRINGE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/METALLIC_-_FRINGE/METALLIC_-_FRINGE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/METALLIC_-_FRINGE/METALLIC_-_FRINGE_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Fringe',
		category: 'Metallic',
		templateCategories: ['Dress'],
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_SEQUIN/WOOL_-_SEQUIN_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_SEQUIN/WOOL_-_SEQUIN_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_SEQUIN/WOOL_-_SEQUIN_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_SEQUIN/WOO_L-__SEQUIN_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_SEQUIN/WOOL_-_SEQUIN_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Sequin',
		category: 'Wool',
		templateCategories: ['Dress', 'Accessories'],
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_RED/YARN_LACE_-_RED_-_ALPHA.jpg',
		materialName: 'Red',
		category: 'Yarn Lace',
		templateCategories: ['Dress'],
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/BLACK_-_360/BLACK_-_360_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/BLACK_-_360/BLACK_-_360_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/BLACK_-_360/BLACK_-_360_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/BLACK_-_360/BLACK_-_360_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/BLACK_-_360/BLACK_-_360_-_ROUGH.jpg',
		alpha: '',
		materialName: '360',
		category: 'Black',
		templateCategories: ['Jumpsuit'],
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/EMBROIDERED_-_HORSEHAIR/EMBROIDERED_-_HORSEHAIR_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/EMBROIDERED_-_HORSEHAIR/EMBROIDERED_-_HORSEHAIR_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/EMBROIDERED_-_HORSEHAIR/EMBROIDERED_-_HORSEHAIR_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/EMBROIDERED_-_HORSEHAIR/EMBROIDERED_-_HORSEHAIR_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/EMBROIDERED_-_HORSEHAIR/EMBROIDERED_-_HORSEHAIR_-_ROUGH.jpg',
		alpha: '',
		materialName: 'Horsehair',
		category: 'Embroidered',
		templateCategories: ['Accessories', 'Dress'],
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_361/WOOL_-_361_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_361/WOOL_-_361_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_361/WOOL_-_361_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_361/WOOL_-_361_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/WOOL_-_361/WOOL_-_361_-_ROUGH.jpg',
		alpha: '',
		materialName: '361',
		category: 'Wool',
		templateCategories: ['Dress', 'Accessories'],
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_RENDER.webp',
		normal: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_NORMAL.jpg',
		baseColor: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_BASE.jpg',
		displacement: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_DISPLACE.jpg',
		roughness: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_ROUGH.jpg',
		alpha: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/fabrics/atelierGourney/root/YARN_LACE_-_WHITE/YARN_LACE_-_WHITE_-_ALPHA.jpg',
		materialName: 'White',
		category: 'Yarn Lace',
		templateCategories: ['Accessories'],
	}
	]
}
