import type {Template} from '../types/template'

// Temporary copy of moidien's templates until we have the new structure ready
export const templates: Record<string, Template[]> = {
	moidien: [
		{
			_id: '1',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_16.png',
			name: 'Item 16',
			avatar: 'Female',
			category: 'Accessories',
			materialId: '',
		},
		{
			_id: '2',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_15.png',
			name: 'Item 15',
			avatar: 'Female',
			category: 'Accessories',
			materialId: '',
		},
		{
			_id: '3',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_14.png',
			name: 'Item 14',
			avatar: 'Female',
			category: 'Accessories',
			materialId: '',
		},
		{
			_id: '4',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_17.png',
			name: 'Item 17',
			avatar: 'Female',
			category: 'Accessories',
			materialId: '',
		},
		{
			_id: '5',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_13.png',
			name: 'Item 13',
			avatar: 'Female',
			category: 'Accessories',
			materialId: '',
		},
		{
			_id: '6',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_10.png',
			name: 'Item 10',
			avatar: 'Female',
			category: 'Accessories',
			materialId: 'Black Pleated Fabric Accessories',
		},
		{
			_id: '7',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_2.png',
			name: 'Item 2',
			avatar: 'Female',
			category: 'Accessories',
			materialId: 'White Pleated Fabric Accessories',
		},
		{
			_id: '8',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Accessories/Item_1.png',
			name: 'Item 1',
			avatar: 'Female',
			category: 'Accessories',
			materialId: 'Black Pleated Fabric Accessories',
		},
		{
			_id: '9',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Dress/Item_3.png',
			name: 'Item 3',
			avatar: 'Female',
			category: 'Dress',
			materialId: 'Taupe Cotton Dress',
		},
		{
			_id: '10',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Shirt/Item_9.png',
			name: 'Item 9',
			avatar: 'Female',
			category: 'Shirt',
			materialId: 'White Pleated Fabric Shirt',
		},
		{
			_id: '11',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Shirt/Item_12.png',
			name: 'Item 12',
			avatar: 'Female',
			category: 'Shirt',
			materialId: 'Black Seersucker Fabric Shirt',
		},
		{
			_id: '12',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Shirt/Item_11.png',
			name: 'Item 11',
			avatar: 'Female',
			category: 'Shirt',
			materialId: 'White Cotton Shirt',
		},
		{
			_id: '13',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Shirt/Item_8.png',
			name: 'Item 8',
			avatar: 'Female',
			category: 'Shirt',
			materialId: 'Navy Crinkle Fabric Shirt',
		},
		{
			_id: '14',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Pants/Item_7.png',
			name: 'Item 7',
			avatar: 'Female',
			category: 'Pants',
			materialId: 'Black Cotton Pants',
		},
		{
			_id: '15',
			thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/moidien/templates/Pants/Item_4.png',
			name: 'Item 4',
			avatar: 'Female',
			category: 'Pants',
			materialId: 'Twill Cotton Pants',
		},
	],
}
