import type {Space} from '../types/types.js'
import {blocks} from './blocks.js'

export const spaces: Space[] = [
	{
		name: 'GẤP',
		slug: 'GAP',
		description: 'MoiDien',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/logo_optimized.webp',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/scene-thumbnail_optimized.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.moidien?.length ?? 0,
		collection: 'moidien',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'The Soul',
		slug: 'the-soul',
		description: 'The Soul',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/the-soul/The+Soul+-+Scene.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/the-soul/The+Soul+-+Scene.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/the-soul/The+Soul+-+Shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.theSoul?.length ?? 0,
		collection: 'theSoul',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Emwear',
		slug: 'emwear',
		description: 'Emwear',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Emwear.png',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/emwear/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/emwear/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/emwear/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.emwear?.length ?? 0,
		collection: 'emwear',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Duality in Radiance',
		slug: 'duality-in-radiance',
		description: 'SHRI',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Shri.png',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/shri/SHRI+-+Scene.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/shri/SHRI+-+Scene.glb',
		includedModelFiles: ['https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/shri/SHRI+-+Shoes.glb'],
		gender: 'female',
		garmentsCount: blocks.shri?.length ?? 0,
		collection: 'shri',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Metamorphosis',
		slug: 'metamorphosis',
		description: 'OOFYA',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SHOES.glb',
		],
		gender: 'female',
		garmentsCount: blocks.oofya?.length ?? 0,
		collection: 'oofya',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Zove',
		slug: 'zove',
		description: 'Zove',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Zove.png',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/zove/ZOVE+-+SCENE.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/zove/ZOVE+-+SCENE.glb',
		includedModelFiles: ['https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/zove/extras/shoes.glb'],
		gender: 'female',
		garmentsCount: blocks.zove?.length ?? 0,
		collection: 'zove',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Movement',
		slug: 'movement',
		description: 'Haruki',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/movement/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/movement/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/movement/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.haruki?.length ?? 0,
		collection: 'haruki',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Essence of her',
		slug: 'essence-of-her',
		description: 'Vaishnavi',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/naishnavi/scene-thumbnail_optimized.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/naishnavi/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/naishnavi/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.vaishnavi?.length ?? 0,
		collection: 'vaishnavi',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Shadow Grace',
		slug: 'shadow-grace',
		description: 'Lost Cause',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/lost-cause/scene-thumbnail_optimized.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/lost-cause/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/lost-cause/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.lostCause?.length ?? 0,
		collection: 'lostCause',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: '9heure19heure',
		slug: '9heure19heuree',
		description: 'ELISE.F',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/eliseF/scene-thumbnail_optimized.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/eliseF/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/eliseF/extras/shoes.glb',
		],
		gender: 'male',
		garmentsCount: blocks.eliseF?.length ?? 0,
		collection: 'eliseF',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Fige dans le temps',
		slug: 'fige-dans-le-temps',
		description: 'Atelier Gourney',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/atelier-gourney/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/atelier-gourney/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/atelier-gourney/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.atelierGourney?.length ?? 0,
		collection: 'atelierGourney',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Imzad-Man',
		slug: 'imzad-man',
		description: 'Imzad',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-male/scene-thumbnail2.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-male/scene-model.glb',
		includedModelFiles: [],
		gender: 'male',
		garmentsCount: blocks.imzadMale?.length ?? 0,
		collection: 'imzadMale',
		isWholesale: false,
		isWorkInProgress: false,
		viewOnly: true,
	},
	{
		name: 'Imzad-Woman',
		slug: 'imzad-woman',
		description: 'Imzad',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-female/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-female/scene-model.glb',
		includedModelFiles: [],
		gender: 'female',
		garmentsCount: blocks.imzadFemale?.length ?? 0,
		collection: 'imzadFemale',
		isWholesale: false,
		isWorkInProgress: false,
		viewOnly: true,
	},
	{
		name: 'One Thousand Poets',
		slug: 'one-thousand-poets',
		description: 'One Thousand Poets',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/one-thousand-poets/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/one-thousand-poets/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/one-thousand-poets/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.oneThousandPoets?.length ?? 0,
		collection: 'oneThousandPoets',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Ja Seng Bu',
		slug: 'ja-seng-bu',
		description: 'Ja Seng Bu',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/ja-seng-bu/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/ja-seng-bu/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/ja-seng-bu/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.jaSengBu?.length ?? 0,
		collection: 'jaSengBu',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Mss Park',
		slug: 'mss-park',
		description: 'Mss Park',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/mss-park/scene-thumbnail.webp',
		scene: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/mss-park/scene-model.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/mss-park/extras/shoes.glb',
		],
		gender: 'female',
		garmentsCount: blocks.mssPark?.length ?? 0,
		collection: 'mssPark',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'CHANGES',
		slug: 'changes',
		description: 'Sapienza University of Rome',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/sapienzaUniversityOfRome/CHANGES+-+3D+SCENE.webp',
		scene:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/sapienzaUniversityOfRome/CHANGES+-+3D+SCENE.glb',
		includedModelFiles: [
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/sapienzaUniversityOfRome/CHANGES+-+3D+SHOES.glb',
		],
		gender: 'female',
		garmentsCount: blocks.sapienzaUniversityOfRome?.length ?? 0,
		collection: 'sapienzaUniversityOfRome',
		isWholesale: false,
		isWorkInProgress: false,
	},
	{
		name: 'Drippy',
		slug: 'drippy',
		description: 'Drippy',
		logo: '',
		env: '/images/envs/brown_photostudio_02.jpg',
		sceneThumbnail: '',
		scene: '',
		includedModelFiles: [],
		gender: 'female',
		garmentsCount: 0,
		collection: 'drippy',
		isWholesale: false,
		isWorkInProgress: false,
	},
]
