import type {Space} from '../types/types.js'
import {collections} from './collections.js'

const sumGarmentsCount = (spaceCollections: string[]) => {
	return spaceCollections.reduce(
		(acc, collectionSlug) => acc + (collections.find(c => c.slug === collectionSlug)?.garmentsCount ?? 0),
		0,
	)
}

export const spaces: Space[] = [
	{
		name: 'Metamorphosis',
		slug: 'metamorphosis',
		description: 'OOFYA',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.webp',
		defaultScene: 'metamorphosis',
		scenes: ['metamorphosis'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['metamorphosis']),
		collections: ['metamorphosis'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: false,
	},
	{
		name: 'H&M',
		slug: 'h&m',
		description: 'H&M',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/lgo-h%26m.webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/H%26M+Scene.png',
		defaultScene: 'h&m',
		scenes: ['h&m'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['h&m']),
		collections: ['h&m'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: false,
	},
	{
		name: 'Drippy Shop',
		slug: 'drippy-shop',
		description: 'Drippy Shop',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.webp',
		defaultScene: 'drippy-shop',
		scenes: ['drippy-shop'],
		gender: 'female',
		garmentsCount: sumGarmentsCount([
			'anyshape',
			'ayarabbim',
			'baum-und-pferdgarten',
			'bloom.womenswear',
			'bupbes',
			'call-me-ari',
			'cecilie-bahnsen',
			'crescent',
			'cuba-vera',
			'dario-mittmann',
			'givenchy',
			'dico',
			'dottie',
			'edini',
			'erroris.ltd',
			'gola',
			'h2b',
			'joie-des-roses',
			'jubin-studio',
			'celeste-studio',
			'just-etro-gang',
			'kido',
			'levents',
			'bad-habits',
			'beachclub.official',
			'berta',
			'cara-club',
			'ceci-cela',
			'celine',
			'colin',
			'demobaza',
			'diane',
			'hani',
			'huelley-rose',
			'hurricane-b',
			'fig.cool-leather',
			'libeworkshop',
			'liniss-official',
			'meanbldv',
			'milk-white',
			'mono-talk',
			'monroe-the-label',
			'naked',
			'nakedandfamousdenim',
			'zd-eye-of-the-storm',
			'abercrombie',
			'oceania-london',
			'cortana',
		]),
		collections: [
			'anyshape',
			'ayarabbim',
			'baum-und-pferdgarten',
			'bloom.womenswear',
			'bupbes',
			'call-me-ari',
			'cecilie-bahnsen',
			'crescent',
			'cuba-vera',
			'dario-mittmann',
			'givenchy',
			'dico',
			'dottie',
			'edini',
			'erroris.ltd',
			'gola',
			'h2b',
			'joie-des-roses',
			'jubin-studio',
			'celeste-studio',
			'just-etro-gang',
			'kido',
			'levents',
			'bad-habits',
			'beachclub.official',
			'berta',
			'cara-club',
			'ceci-cela',
			'celine',
			'colin',
			'demobaza',
			'diane',
			'hani',
			'huelley-rose',
			'hurricane-b',
			'fig.cool-leather',
			'libeworkshop',
			'liniss-official',
			'meanbldv',
			'milk-white',
			'mono-talk',
			'monroe-the-label',
			'naked',
			'nakedandfamousdenim',
			'zd-eye-of-the-storm',
			'abercrombie',
			'oceania-london',
			'cortana',
		],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: false,
	},
]
