import type {Space} from '../types/types.js'
import {collections} from './collections.js'

const noImageUrl = new URL('../images/no-image.jpg', import.meta.url).href

const sumGarmentsCount = (spaceCollections: string[]) => {
	return spaceCollections.reduce(
		(acc, collectionSlug) => acc + (collections.find(c => c.slug === collectionSlug)?.garmentsCount ?? 0),
		0,
	)
}

export const spaces: Space[] = [
	{
		name: 'GẤP',
		slug: 'GAP',
		description: 'gap',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/logo_optimized.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/moidien/scene-thumbnail_optimized.webp',
		defaultScene: 'gap',
		scenes: ['gap'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['gap']),
		collections: ['gap'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'The Soul',
		slug: 'the-soul',
		description: 'The Soul',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/TS-LOGO-_1_.webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/the-soul/The+Soul+-+Scene.webp',
		defaultScene: 'the-soul',
		scenes: ['the-soul'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['the-soul']),
		collections: ['the-soul'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Emwear',
		slug: 'emwear',
		description: 'Emwear',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Emwear.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/emwear/scene-thumbnail.webp',
		defaultScene: 'emwear',
		scenes: ['emwear'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['emwear']),
		collections: ['emwear'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Duality in Radiance',
		slug: 'duality-in-radiance',
		description: 'SHRI',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Shri.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/shri/SHRI+-+Scene.webp',
		defaultScene: 'duality-in-radiance',
		scenes: ['duality-in-radiance'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['duality-in-radiance']),
		collections: ['duality-in-radiance'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Metamorphosis (Ipose)',
		slug: 'metamorphosis-ipose',
		description: 'OOFYA',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.webp',
		defaultScene: 'metamorphosis',
		scenes: ['metamorphosis'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['metamorphosis']),
		collections: ['metamorphosis'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Zove',
		slug: 'zove',
		description: 'Zove',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Zove.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/zove/ZOVE+-+SCENE.webp',
		defaultScene: 'zove',
		scenes: ['zove'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['zove']),
		collections: ['zove'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Movement',
		slug: 'movement',
		description: 'Haruki',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/HARUKI+ISHIII+(1).webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/movement/scene-thumbnail.webp',
		defaultScene: 'movement',
		scenes: ['movement'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['movement']),
		collections: ['movement'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Essence of her',
		slug: 'essence-of-her',
		description: 'Vaishnavi',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Vaishnavi.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/naishnavi/scene-thumbnail_optimized.webp',
		defaultScene: 'essence-of-her',
		scenes: ['essence-of-her'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['essence-of-her']),
		collections: ['essence-of-her'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Shadow Grace',
		slug: 'shadow-grace',
		description: 'Lost Cause',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/LOST-CAUSE.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/lost-cause/scene-thumbnail_optimized.webp',
		defaultScene: 'shadow-grace',
		scenes: ['shadow-grace'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['shadow-grace']),
		collections: ['shadow-grace'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: '9heure19heure',
		slug: '9heure19heure',
		description: 'ELISE.F',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Elise.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/eliseF/scene-thumbnail_optimized.webp',
		defaultScene: '9heure19heure',
		scenes: ['9heure19heure'],
		gender: 'male',
		garmentsCount: sumGarmentsCount(['9heure19heure']),
		collections: ['9heure19heure'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Fige dans le temps',
		slug: 'fige-dans-le-temps',
		description: 'Atelier Gourney',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Atelier+Gourney+(1).webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/atelier-gourney/scene-thumbnail.webp',
		defaultScene: 'fige-dans-le-temps',
		scenes: ['fige-dans-le-temps'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['fige-dans-le-temps']),
		collections: ['fige-dans-le-temps'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Imzad-Man',
		slug: 'imzad-man',
		description: 'Imzad',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/IMZAD.webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-male/scene-thumbnail2.webp',
		defaultScene: 'imzad-man',
		scenes: ['imzad-man'],
		gender: 'male',
		garmentsCount: sumGarmentsCount(['imzad-man']),
		collections: ['imzad-man'],
		isWholesale: false,
		isWorkInProgress: false,
		viewOnly: true,
		isHidden: true,
	},
	{
		name: 'Imzad-Woman',
		slug: 'imzad-woman',
		description: 'Imzad',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/IMZAD.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/imzad-female/scene-thumbnail.webp',
		defaultScene: 'imzad-woman',
		scenes: ['imzad-woman'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['imzad-woman']),
		collections: ['imzad-woman'],
		isWholesale: false,
		isWorkInProgress: false,
		viewOnly: true,
		isHidden: true,
	},
	{
		name: 'One Thousand Poets',
		slug: 'one-thousand-poets',
		description: 'One Thousand Poets',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/One+thousand+poets.webp',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/one-thousand-poets/scene-thumbnail.webp',
		defaultScene: 'one-thousand-poets',
		scenes: ['one-thousand-poets'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['one-thousand-poets']),
		collections: ['one-thousand-poets'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Ja Seng Bu',
		slug: 'ja-seng-bu',
		description: 'Ja Seng Bu',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/Seng.webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/ja-seng-bu/scene-thumbnail.webp',
		defaultScene: 'ja-seng-bu',
		scenes: ['ja-seng-bu'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['ja-seng-bu']),
		collections: ['ja-seng-bu'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Mss Park',
		slug: 'mss-park',
		description: 'Mss Park',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/MISS-PARK-logo_full_-_1_.webp',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/mss-park/scene-thumbnail.webp',
		defaultScene: 'mss-park',
		scenes: ['mss-park'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['mss-park']),
		collections: ['mss-park'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'CHANGES',
		slug: 'changes',
		description: 'Sapienza University of Rome',
		logo: '',
		thumbnail:
			'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/sapienzaUniversityOfRome/CHANGES+-+3D+SCENE.webp',
		defaultScene: 'changes',
		scenes: ['changes'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['changes']),
		collections: ['changes'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: true,
	},
	{
		name: 'Metamorphosis',
		slug: 'metamorphosis',
		description: 'OOFYA',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/Logo-1/Oofya.png',
		thumbnail: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/oofya/OOFYA+-+SCENE.webp',
		defaultScene: 'metamorphosis',
		scenes: ['metamorphosis'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['animation-test']),
		collections: ['animation-test'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: false,
	},
	{
		name: 'PFW 2026',
		slug: 'pfw-2026',
		description: 'PFW 2026',
		logo: '',
		defaultScene: 'pfw-2026',
		scenes: ['pfw-2026'],
		gender: 'female',
		garmentsCount: sumGarmentsCount([
			'anyshape',
			'baum-und-pferdgarten',
			'bloom.womenswear',
			'cecilie-bahnsen',
			'crescent',
			'dario-mittmann',
			'david-black',
			'diane',
			'dico',
			'dottie',
			'erroris.ltd',
			'gola',
			'h2b',
			'joie-des-roses',
			'jubin-studio',
			'julian-prohaska',
			'kido',
			'levents',
			'ononmm',
			'pindiga-ranjith-kumar',
			'pradies',
			'bad-habits',
			'beachclub.official',
			'cara-club',
			'demobaza',
			'hani',
			'huelley-rose',
			'hurricane-b',
			'fig.cool-leather',
			'libeworkshop',
			'mono-talk',
			'naked',
			'push-push',
			'raxada',
			'rechick',
			'ridkid',
			'rotate',
			'salteye',
			'skall',
			'so-vintage-official',
			'sora.m_design',
			'ssdslsns',
			'stevie-crowne',
			'tsun',
			'tubycatu',
			'whiteplan',
			'zd-eye-of-the-storm',
			'katalog-1811',
		]),
		collections: [
			'anyshape',
			'baum-und-pferdgarten',
			'bloom.womenswear',
			'cecilie-bahnsen',
			'crescent',
			'dario-mittmann',
			'david-black',
			'diane',
			'dico',
			'dottie',
			'erroris.ltd',
			'gola',
			'h2b',
			'joie-des-roses',
			'jubin-studio',
			'julian-prohaska',
			'kido',
			'levents',
			'ononmm',
			'pindiga-ranjith-kumar',
			'pradies',
			'bad-habits',
			'beachclub.official',
			'cara-club',
			'demobaza',
			'hani',
			'huelley-rose',
			'hurricane-b',
			'fig.cool-leather',
			'libeworkshop',
			'mono-talk',
			'naked',
			'push-push',
			'raxada',
			'rechick',
			'ridkid',
			'rotate',
			'salteye',
			'skall',
			'so-vintage-official',
			'sora.m_design',
			'ssdslsns',
			'stevie-crowne',
			'tsun',
			'tubycatu',
			'whiteplan',
			'zd-eye-of-the-storm',
			'katalog-1811',
		],
		isWholesale: false,
		isWorkInProgress: true,
		isHidden: false,
	},
	{
		name: 'PFW 2026 Male',
		slug: 'pfw-2026-male',
		description: 'PFW 2026 Male',
		logo: '',
		defaultScene: 'pfw-2026',
		scenes: ['pfw-2026'],
		gender: 'male',
		garmentsCount: sumGarmentsCount(['lider', 'paradise-saigon', 'vinaygaia']),
		collections: ['lider', 'paradise-saigon', 'vinaygaia'],
		isWholesale: false,
		isWorkInProgress: true,
		isHidden: true,
	},
	{
		name: 'H&M',
		slug: 'h&m',
		description: 'H&M',
		logo: 'https://d1e6s1h8cqcr26.cloudfront.net/drippy-app/drippy-app-3D/brands/h%26m/H%26M+Scene.png',
		thumbnail: noImageUrl,
		defaultScene: 'h&m',
		scenes: ['h&m'],
		gender: 'female',
		garmentsCount: sumGarmentsCount(['h&m']),
		collections: ['h&m'],
		isWholesale: false,
		isWorkInProgress: false,
		isHidden: false,
	},
]
