import type {Template} from '../types/template'

export const templates: Record<string, Template[]> = {
	speed: [
	{
		_id: '1',
		thumb: new URL('../images/speed/Look 8_3.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 8_3.gltf', import.meta.url).href,
		name: 'Look 8_3',
		avatar: 'Male',
	},
	{
		_id: '2',
		thumb: new URL('../images/speed/Look 8_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 8_2.gltf', import.meta.url).href,
		name: 'Look 8_2',
		avatar: 'Male',
	},
	{
		_id: '3',
		thumb: new URL('../images/speed/Look 8_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 8_1.gltf', import.meta.url).href,
		name: 'Look 8_1',
		avatar: 'Male',
	},
	{
		_id: '4',
		thumb: new URL('../images/speed/Look 11_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 11_2.gltf', import.meta.url).href,
		name: 'Look 11_2',
		avatar: 'Male',
	},
	{
		_id: '5',
		thumb: new URL('../images/speed/Look 12.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 12.gltf', import.meta.url).href,
		name: 'Look 12',
		avatar: 'Male',
	},
	{
		_id: '6',
		thumb: new URL('../images/speed/Look 11_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 11_1.gltf', import.meta.url).href,
		name: 'Look 11_1',
		avatar: 'Male',
	},
	{
		_id: '7',
		thumb: new URL('../images/speed/Look 10_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 10_2.gltf', import.meta.url).href,
		name: 'Look 10_2',
		avatar: 'Male',
	},
	{
		_id: '8',
		thumb: new URL('../images/speed/Look 10_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 10_1.gltf', import.meta.url).href,
		name: 'Look 10_1',
		avatar: 'Male',
	},
	{
		_id: '9',
		thumb: new URL('../images/speed/Look 9_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 9_1.gltf', import.meta.url).href,
		name: 'Look 9_1',
		avatar: 'Male',
	},
	{
		_id: '10',
		thumb: new URL('../images/speed/Look 9_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 9_2.gltf', import.meta.url).href,
		name: 'Look 9_2',
		avatar: 'Male',
	},
	{
		_id: '11',
		thumb: new URL('../images/speed/Look 5_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 5_2.gltf', import.meta.url).href,
		name: 'Look 5_2',
		avatar: 'Male',
	},
	{
		_id: '12',
		thumb: new URL('../images/speed/Look 5_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 5_1.gltf', import.meta.url).href,
		name: 'Look 5_1',
		avatar: 'Male',
	},
	{
		_id: '13',
		thumb: new URL('../images/speed/Look 4_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 4_1.gltf', import.meta.url).href,
		name: 'Look 4_1',
		avatar: 'Male',
	},
	{
		_id: '14',
		thumb: new URL('../images/speed/Look 3_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 3_1.gltf', import.meta.url).href,
		name: 'Look 3_1',
		avatar: 'Male',
	},
	{
		_id: '15',
		thumb: new URL('../images/speed/Look 2_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 2_2.gltf', import.meta.url).href,
		name: 'Look 2_2',
		avatar: 'Male',
	},
	{
		_id: '16',
		thumb: new URL('../images/speed/Look 2_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 2_1.gltf', import.meta.url).href,
		name: 'Look 2_1',
		avatar: 'Male',
	},
	{
		_id: '17',
		thumb: new URL('../images/speed/Look 1_3.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 1_3.gltf', import.meta.url).href,
		name: 'Look 1_3',
		avatar: 'Male',
	},
	{
		_id: '18',
		thumb: new URL('../images/speed/Look 1_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 1_2.gltf', import.meta.url).href,
		name: 'Look 1_2',
		avatar: 'Male',
	},
	{
		_id: '19',
		thumb: new URL('../images/speed/Look 1_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 1_1.gltf', import.meta.url).href,
		name: 'Look 1_1',
		avatar: 'Male',
	},
	{
		_id: '20',
		thumb: new URL('../images/speed/Look 7_3.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 7_3.gltf', import.meta.url).href,
		name: 'Look 7_3',
		avatar: 'Male',
	},
	{
		_id: '21',
		thumb: new URL('../images/speed/Look 7_2.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 7_2.gltf', import.meta.url).href,
		name: 'Look 7_2',
		avatar: 'Male',
	},
	{
		_id: '22',
		thumb: new URL('../images/speed/Look 7_1.png', import.meta.url).href,
		modelFile: new URL('../models/speed/Look 7_1.gltf', import.meta.url).href,
		name: 'Look 7_1',
		avatar: 'Male',
	}
	]
}
