import type {Template} from '../types/template'

export const templates: Record<string, Template[]> = {
	speed: [
	{
		_id: '1',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%208_3.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+8_3.gltf',
		name: 'Look 8_3',
		avatar: 'Male',
	},
	{
		_id: '2',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%208_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+8_2.gltf',
		name: 'Look 8_2',
		avatar: 'Male',
	},
	{
		_id: '3',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%208_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look%208_1.gltf',
		name: 'Look 8_1',
		avatar: 'Male',
	},
	{
		_id: '4',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%2011_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+11_2.gltf',
		name: 'Look 11_2',
		avatar: 'Male',
	},
	{
		_id: '5',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%2012.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+12.gltf',
		name: 'Look 12',
		avatar: 'Male',
	},
	{
		_id: '6',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%2011_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+11_1.gltf',
		name: 'Look 11_1',
		avatar: 'Male',
	},
	{
		_id: '7',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%2010_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+10_2.gltf',
		name: 'Look 10_2',
		avatar: 'Male',
	},
	{
		_id: '8',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%2010_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+10_1.gltf',
		name: 'Look 10_1',
		avatar: 'Male',
	},
	{
		_id: '9',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%209_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+9_1.gltf',
		name: 'Look 9_1',
		avatar: 'Male',
	},
	{
		_id: '10',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%209_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+9_2.gltf',
		name: 'Look 9_2',
		avatar: 'Male',
	},
	{
		_id: '11',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%205_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+5_2.gltf',
		name: 'Look 5_2',
		avatar: 'Male',
	},
	{
		_id: '12',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%205_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+5_1.gltf',
		name: 'Look 5_1',
		avatar: 'Male',
	},
	{
		_id: '13',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%204_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+4_1.gltf',
		name: 'Look 4_1',
		avatar: 'Male',
	},
	{
		_id: '14',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%203_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+3_1.gltf',
		name: 'Look 3_1',
		avatar: 'Male',
	},
	{
		_id: '15',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%202_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+2_2.gltf',
		name: 'Look 2_2',
		avatar: 'Male',
	},
	{
		_id: '16',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%202_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+2_1.gltf',
		name: 'Look 2_1',
		avatar: 'Male',
	},
	{
		_id: '17',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%201_3.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+1_3.gltf',
		name: 'Look 1_3',
		avatar: 'Male',
	},
	{
		_id: '18',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%201_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+1_2.gltf',
		name: 'Look 1_2',
		avatar: 'Male',
	},
	{
		_id: '19',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%201_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+1_1.gltf',
		name: 'Look 1_1',
		avatar: 'Male',
	},
	{
		_id: '20',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%207_3.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+7_3.gltf',
		name: 'Look 7_3',
		avatar: 'Male',
	},
	{
		_id: '21',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%207_2.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+7_2.gltf',
		name: 'Look 7_2',
		avatar: 'Male',
	},
	{
		_id: '22',
		thumb: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/images/speed/Look%207_1.png',
		modelFile: 'https://drippy3d-prod-eu.s3.eu-west-3.amazonaws.com/models/speed/Look+7_1.gltf',
		name: 'Look 7_1',
		avatar: 'Male',
	}
	]
}
