name: Test

on:
    pull_request:
        branches: [dev, main]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # todo update esbuild script for windows
                os: [ubuntu-latest, macos-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install dependencies and build
              # TODO versioned meteor install
              run: |
                  npm install -g meteor --foreground-script
                  PATH=~/.meteor:$PATH npm clean-install

            - name: Lint
              run: npm run lint

            - name: Formatting check
              run: npm run prettier:check

            - name: Run tests
              run: npm test
